package fr.smartprod.paperdms.monitoring.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlertRuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertRuleAllPropertiesEquals(AlertRule expected, AlertRule actual) {
        assertAlertRuleAutoGeneratedPropertiesEquals(expected, actual);
        assertAlertRuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertRuleAllUpdatablePropertiesEquals(AlertRule expected, AlertRule actual) {
        assertAlertRuleUpdatableFieldsEquals(expected, actual);
        assertAlertRuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertRuleAutoGeneratedPropertiesEquals(AlertRule expected, AlertRule actual) {
        assertThat(actual)
            .as("Verify AlertRule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertRuleUpdatableFieldsEquals(AlertRule expected, AlertRule actual) {
        assertThat(actual)
            .as("Verify AlertRule relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getAlertType()).as("check alertType").isEqualTo(expected.getAlertType()))
            .satisfies(a -> assertThat(a.getConditions()).as("check conditions").isEqualTo(expected.getConditions()))
            .satisfies(a -> assertThat(a.getSeverity()).as("check severity").isEqualTo(expected.getSeverity()))
            .satisfies(a -> assertThat(a.getRecipients()).as("check recipients").isEqualTo(expected.getRecipients()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getTriggerCount()).as("check triggerCount").isEqualTo(expected.getTriggerCount()))
            .satisfies(a -> assertThat(a.getLastTriggered()).as("check lastTriggered").isEqualTo(expected.getLastTriggered()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlertRuleUpdatableRelationshipsEquals(AlertRule expected, AlertRule actual) {
        // empty method
    }
}
