package fr.smartprod.paperdms.monitoring.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentWatchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentWatchAllPropertiesEquals(DocumentWatch expected, DocumentWatch actual) {
        assertDocumentWatchAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentWatchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentWatchAllUpdatablePropertiesEquals(DocumentWatch expected, DocumentWatch actual) {
        assertDocumentWatchUpdatableFieldsEquals(expected, actual);
        assertDocumentWatchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentWatchAutoGeneratedPropertiesEquals(DocumentWatch expected, DocumentWatch actual) {
        assertThat(actual)
            .as("Verify DocumentWatch auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentWatchUpdatableFieldsEquals(DocumentWatch expected, DocumentWatch actual) {
        assertThat(actual)
            .as("Verify DocumentWatch relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getWatchType()).as("check watchType").isEqualTo(expected.getWatchType()))
            .satisfies(a -> assertThat(a.getNotifyOnView()).as("check notifyOnView").isEqualTo(expected.getNotifyOnView()))
            .satisfies(a -> assertThat(a.getNotifyOnDownload()).as("check notifyOnDownload").isEqualTo(expected.getNotifyOnDownload()))
            .satisfies(a -> assertThat(a.getNotifyOnModify()).as("check notifyOnModify").isEqualTo(expected.getNotifyOnModify()))
            .satisfies(a -> assertThat(a.getNotifyOnShare()).as("check notifyOnShare").isEqualTo(expected.getNotifyOnShare()))
            .satisfies(a -> assertThat(a.getNotifyOnDelete()).as("check notifyOnDelete").isEqualTo(expected.getNotifyOnDelete()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentWatchUpdatableRelationshipsEquals(DocumentWatch expected, DocumentWatch actual) {
        // empty method
    }
}
