package fr.smartprod.paperdms.monitoring.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MaintenanceTaskAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceTaskAllPropertiesEquals(MaintenanceTask expected, MaintenanceTask actual) {
        assertMaintenanceTaskAutoGeneratedPropertiesEquals(expected, actual);
        assertMaintenanceTaskAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceTaskAllUpdatablePropertiesEquals(MaintenanceTask expected, MaintenanceTask actual) {
        assertMaintenanceTaskUpdatableFieldsEquals(expected, actual);
        assertMaintenanceTaskUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceTaskAutoGeneratedPropertiesEquals(MaintenanceTask expected, MaintenanceTask actual) {
        assertThat(actual)
            .as("Verify MaintenanceTask auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceTaskUpdatableFieldsEquals(MaintenanceTask expected, MaintenanceTask actual) {
        assertThat(actual)
            .as("Verify MaintenanceTask relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getTaskType()).as("check taskType").isEqualTo(expected.getTaskType()))
            .satisfies(a -> assertThat(a.getSchedule()).as("check schedule").isEqualTo(expected.getSchedule()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getLastRun()).as("check lastRun").isEqualTo(expected.getLastRun()))
            .satisfies(a -> assertThat(a.getNextRun()).as("check nextRun").isEqualTo(expected.getNextRun()))
            .satisfies(a -> assertThat(a.getDuration()).as("check duration").isEqualTo(expected.getDuration()))
            .satisfies(a -> assertThat(a.getRecordsProcessed()).as("check recordsProcessed").isEqualTo(expected.getRecordsProcessed()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceTaskUpdatableRelationshipsEquals(MaintenanceTask expected, MaintenanceTask actual) {
        // empty method
    }
}
