package fr.smartprod.paperdms.monitoring.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MonitoringAlertAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringAlertAllPropertiesEquals(MonitoringAlert expected, MonitoringAlert actual) {
        assertMonitoringAlertAutoGeneratedPropertiesEquals(expected, actual);
        assertMonitoringAlertAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringAlertAllUpdatablePropertiesEquals(MonitoringAlert expected, MonitoringAlert actual) {
        assertMonitoringAlertUpdatableFieldsEquals(expected, actual);
        assertMonitoringAlertUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringAlertAutoGeneratedPropertiesEquals(MonitoringAlert expected, MonitoringAlert actual) {
        assertThat(actual)
            .as("Verify MonitoringAlert auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringAlertUpdatableFieldsEquals(MonitoringAlert expected, MonitoringAlert actual) {
        assertThat(actual)
            .as("Verify MonitoringAlert relevant properties")
            .satisfies(a -> assertThat(a.getSeverity()).as("check severity").isEqualTo(expected.getSeverity()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getEntityType()).as("check entityType").isEqualTo(expected.getEntityType()))
            .satisfies(a -> assertThat(a.getEntityName()).as("check entityName").isEqualTo(expected.getEntityName()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getTriggeredDate()).as("check triggeredDate").isEqualTo(expected.getTriggeredDate()))
            .satisfies(a -> assertThat(a.getAcknowledgedBy()).as("check acknowledgedBy").isEqualTo(expected.getAcknowledgedBy()))
            .satisfies(a -> assertThat(a.getAcknowledgedDate()).as("check acknowledgedDate").isEqualTo(expected.getAcknowledgedDate()))
            .satisfies(a -> assertThat(a.getResolvedBy()).as("check resolvedBy").isEqualTo(expected.getResolvedBy()))
            .satisfies(a -> assertThat(a.getResolvedDate()).as("check resolvedDate").isEqualTo(expected.getResolvedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringAlertUpdatableRelationshipsEquals(MonitoringAlert expected, MonitoringAlert actual) {
        assertThat(actual)
            .as("Verify MonitoringAlert relationships")
            .satisfies(a -> assertThat(a.getAlertRule()).as("check alertRule").isEqualTo(expected.getAlertRule()));
    }
}
