package fr.smartprod.paperdms.monitoring.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MonitoringDocumentWatchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringDocumentWatchAllPropertiesEquals(MonitoringDocumentWatch expected, MonitoringDocumentWatch actual) {
        assertMonitoringDocumentWatchAutoGeneratedPropertiesEquals(expected, actual);
        assertMonitoringDocumentWatchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringDocumentWatchAllUpdatablePropertiesEquals(
        MonitoringDocumentWatch expected,
        MonitoringDocumentWatch actual
    ) {
        assertMonitoringDocumentWatchUpdatableFieldsEquals(expected, actual);
        assertMonitoringDocumentWatchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringDocumentWatchAutoGeneratedPropertiesEquals(
        MonitoringDocumentWatch expected,
        MonitoringDocumentWatch actual
    ) {
        assertThat(actual)
            .as("Verify MonitoringDocumentWatch auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringDocumentWatchUpdatableFieldsEquals(
        MonitoringDocumentWatch expected,
        MonitoringDocumentWatch actual
    ) {
        assertThat(actual)
            .as("Verify MonitoringDocumentWatch relevant properties")
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getWatchType()).as("check watchType").isEqualTo(expected.getWatchType()))
            .satisfies(a -> assertThat(a.getNotifyOnView()).as("check notifyOnView").isEqualTo(expected.getNotifyOnView()))
            .satisfies(a -> assertThat(a.getNotifyOnDownload()).as("check notifyOnDownload").isEqualTo(expected.getNotifyOnDownload()))
            .satisfies(a -> assertThat(a.getNotifyOnModify()).as("check notifyOnModify").isEqualTo(expected.getNotifyOnModify()))
            .satisfies(a -> assertThat(a.getNotifyOnShare()).as("check notifyOnShare").isEqualTo(expected.getNotifyOnShare()))
            .satisfies(a -> assertThat(a.getNotifyOnDelete()).as("check notifyOnDelete").isEqualTo(expected.getNotifyOnDelete()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringDocumentWatchUpdatableRelationshipsEquals(
        MonitoringDocumentWatch expected,
        MonitoringDocumentWatch actual
    ) {
        // empty method
    }
}
