package fr.smartprod.paperdms.reporting.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DashboardWidgetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDashboardWidgetAllPropertiesEquals(DashboardWidget expected, DashboardWidget actual) {
        assertDashboardWidgetAutoGeneratedPropertiesEquals(expected, actual);
        assertDashboardWidgetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDashboardWidgetAllUpdatablePropertiesEquals(DashboardWidget expected, DashboardWidget actual) {
        assertDashboardWidgetUpdatableFieldsEquals(expected, actual);
        assertDashboardWidgetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDashboardWidgetAutoGeneratedPropertiesEquals(DashboardWidget expected, DashboardWidget actual) {
        assertThat(actual)
            .as("Verify DashboardWidget auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDashboardWidgetUpdatableFieldsEquals(DashboardWidget expected, DashboardWidget actual) {
        assertThat(actual)
            .as("Verify DashboardWidget relevant properties")
            .satisfies(a -> assertThat(a.getDashboardId()).as("check dashboardId").isEqualTo(expected.getDashboardId()))
            .satisfies(a -> assertThat(a.getWidgetType()).as("check widgetType").isEqualTo(expected.getWidgetType()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getConfiguration()).as("check configuration").isEqualTo(expected.getConfiguration()))
            .satisfies(a -> assertThat(a.getDataSource()).as("check dataSource").isEqualTo(expected.getDataSource()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getSizeX()).as("check sizeX").isEqualTo(expected.getSizeX()))
            .satisfies(a -> assertThat(a.getSizeY()).as("check sizeY").isEqualTo(expected.getSizeY()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDashboardWidgetUpdatableRelationshipsEquals(DashboardWidget expected, DashboardWidget actual) {
        assertThat(actual)
            .as("Verify DashboardWidget relationships")
            .satisfies(a -> assertThat(a.getDashboard()).as("check dashboard").isEqualTo(expected.getDashboard()));
    }
}
