package fr.smartprod.paperdms.reporting.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PerformanceMetricAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerformanceMetricAllPropertiesEquals(PerformanceMetric expected, PerformanceMetric actual) {
        assertPerformanceMetricAutoGeneratedPropertiesEquals(expected, actual);
        assertPerformanceMetricAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerformanceMetricAllUpdatablePropertiesEquals(PerformanceMetric expected, PerformanceMetric actual) {
        assertPerformanceMetricUpdatableFieldsEquals(expected, actual);
        assertPerformanceMetricUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerformanceMetricAutoGeneratedPropertiesEquals(PerformanceMetric expected, PerformanceMetric actual) {
        assertThat(actual)
            .as("Verify PerformanceMetric auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerformanceMetricUpdatableFieldsEquals(PerformanceMetric expected, PerformanceMetric actual) {
        assertThat(actual)
            .as("Verify PerformanceMetric relevant properties")
            .satisfies(a -> assertThat(a.getMetricName()).as("check metricName").isEqualTo(expected.getMetricName()))
            .satisfies(a -> assertThat(a.getMetricType()).as("check metricType").isEqualTo(expected.getMetricType()))
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()))
            .satisfies(a -> assertThat(a.getServiceName()).as("check serviceName").isEqualTo(expected.getServiceName()))
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerformanceMetricUpdatableRelationshipsEquals(PerformanceMetric expected, PerformanceMetric actual) {
        // empty method
    }
}
