package fr.smartprod.paperdms.reporting.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReportingDashboardAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingDashboardAllPropertiesEquals(ReportingDashboard expected, ReportingDashboard actual) {
        assertReportingDashboardAutoGeneratedPropertiesEquals(expected, actual);
        assertReportingDashboardAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingDashboardAllUpdatablePropertiesEquals(ReportingDashboard expected, ReportingDashboard actual) {
        assertReportingDashboardUpdatableFieldsEquals(expected, actual);
        assertReportingDashboardUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingDashboardAutoGeneratedPropertiesEquals(ReportingDashboard expected, ReportingDashboard actual) {
        assertThat(actual)
            .as("Verify ReportingDashboard auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingDashboardUpdatableFieldsEquals(ReportingDashboard expected, ReportingDashboard actual) {
        assertThat(actual)
            .as("Verify ReportingDashboard relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getIsPublic()).as("check isPublic").isEqualTo(expected.getIsPublic()))
            .satisfies(a -> assertThat(a.getLayout()).as("check layout").isEqualTo(expected.getLayout()))
            .satisfies(a -> assertThat(a.getRefreshInterval()).as("check refreshInterval").isEqualTo(expected.getRefreshInterval()))
            .satisfies(a -> assertThat(a.getIsDefault()).as("check isDefault").isEqualTo(expected.getIsDefault()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingDashboardUpdatableRelationshipsEquals(ReportingDashboard expected, ReportingDashboard actual) {
        // empty method
    }
}
