package fr.smartprod.paperdms.reporting.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReportExecutionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportExecutionAllPropertiesEquals(ReportExecution expected, ReportExecution actual) {
        assertReportExecutionAutoGeneratedPropertiesEquals(expected, actual);
        assertReportExecutionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportExecutionAllUpdatablePropertiesEquals(ReportExecution expected, ReportExecution actual) {
        assertReportExecutionUpdatableFieldsEquals(expected, actual);
        assertReportExecutionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportExecutionAutoGeneratedPropertiesEquals(ReportExecution expected, ReportExecution actual) {
        assertThat(actual)
            .as("Verify ReportExecution auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportExecutionUpdatableFieldsEquals(ReportExecution expected, ReportExecution actual) {
        assertThat(actual)
            .as("Verify ReportExecution relevant properties")
            .satisfies(a -> assertThat(a.getScheduledReportId()).as("check scheduledReportId").isEqualTo(expected.getScheduledReportId()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getRecordsProcessed()).as("check recordsProcessed").isEqualTo(expected.getRecordsProcessed()))
            .satisfies(a -> assertThat(a.getOutputS3Key()).as("check outputS3Key").isEqualTo(expected.getOutputS3Key()))
            .satisfies(a -> assertThat(a.getOutputSize()).as("check outputSize").isEqualTo(expected.getOutputSize()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportExecutionUpdatableRelationshipsEquals(ReportExecution expected, ReportExecution actual) {
        assertThat(actual)
            .as("Verify ReportExecution relationships")
            .satisfies(a -> assertThat(a.getScheduledReport()).as("check scheduledReport").isEqualTo(expected.getScheduledReport()));
    }
}
