package fr.smartprod.paperdms.reporting.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReportingPerformanceMetricAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingPerformanceMetricAllPropertiesEquals(
        ReportingPerformanceMetric expected,
        ReportingPerformanceMetric actual
    ) {
        assertReportingPerformanceMetricAutoGeneratedPropertiesEquals(expected, actual);
        assertReportingPerformanceMetricAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingPerformanceMetricAllUpdatablePropertiesEquals(
        ReportingPerformanceMetric expected,
        ReportingPerformanceMetric actual
    ) {
        assertReportingPerformanceMetricUpdatableFieldsEquals(expected, actual);
        assertReportingPerformanceMetricUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingPerformanceMetricAutoGeneratedPropertiesEquals(
        ReportingPerformanceMetric expected,
        ReportingPerformanceMetric actual
    ) {
        assertThat(actual)
            .as("Verify ReportingPerformanceMetric auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingPerformanceMetricUpdatableFieldsEquals(
        ReportingPerformanceMetric expected,
        ReportingPerformanceMetric actual
    ) {
        assertThat(actual)
            .as("Verify ReportingPerformanceMetric relevant properties")
            .satisfies(a -> assertThat(a.getMetricName()).as("check metricName").isEqualTo(expected.getMetricName()))
            .satisfies(a -> assertThat(a.getMetricType()).as("check metricType").isEqualTo(expected.getMetricType()))
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()))
            .satisfies(a -> assertThat(a.getServiceName()).as("check serviceName").isEqualTo(expected.getServiceName()))
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingPerformanceMetricUpdatableRelationshipsEquals(
        ReportingPerformanceMetric expected,
        ReportingPerformanceMetric actual
    ) {
        // empty method
    }
}
