package com.ged.ocr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OcrResultAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrResultAllPropertiesEquals(OcrResult expected, OcrResult actual) {
        assertOcrResultAutoGeneratedPropertiesEquals(expected, actual);
        assertOcrResultAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrResultAllUpdatablePropertiesEquals(OcrResult expected, OcrResult actual) {
        assertOcrResultUpdatableFieldsEquals(expected, actual);
        assertOcrResultUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrResultAutoGeneratedPropertiesEquals(OcrResult expected, OcrResult actual) {
        assertThat(actual)
            .as("Verify OcrResult auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrResultUpdatableFieldsEquals(OcrResult expected, OcrResult actual) {
        assertThat(actual)
            .as("Verify OcrResult relevant properties")
            .satisfies(a -> assertThat(a.getPageNumber()).as("check pageNumber").isEqualTo(expected.getPageNumber()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.gets3ResultKey()).as("check s3ResultKey").isEqualTo(expected.gets3ResultKey()))
            .satisfies(a -> assertThat(a.getBoundingBoxes()).as("check boundingBoxes").isEqualTo(expected.getBoundingBoxes()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()))
            .satisfies(a -> assertThat(a.getWordCount()).as("check wordCount").isEqualTo(expected.getWordCount()))
            .satisfies(a -> assertThat(a.getProcessedDate()).as("check processedDate").isEqualTo(expected.getProcessedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrResultUpdatableRelationshipsEquals(OcrResult expected, OcrResult actual) {
        assertThat(actual)
            .as("Verify OcrResult relationships")
            .satisfies(a -> assertThat(a.getJob()).as("check job").isEqualTo(expected.getJob()));
    }
}
