package com.ged.ocr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TikaConfigurationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTikaConfigurationAllPropertiesEquals(TikaConfiguration expected, TikaConfiguration actual) {
        assertTikaConfigurationAutoGeneratedPropertiesEquals(expected, actual);
        assertTikaConfigurationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTikaConfigurationAllUpdatablePropertiesEquals(TikaConfiguration expected, TikaConfiguration actual) {
        assertTikaConfigurationUpdatableFieldsEquals(expected, actual);
        assertTikaConfigurationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTikaConfigurationAutoGeneratedPropertiesEquals(TikaConfiguration expected, TikaConfiguration actual) {
        assertThat(actual)
            .as("Verify TikaConfiguration auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTikaConfigurationUpdatableFieldsEquals(TikaConfiguration expected, TikaConfiguration actual) {
        assertThat(actual)
            .as("Verify TikaConfiguration relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getEndpoint()).as("check endpoint").isEqualTo(expected.getEndpoint()))
            .satisfies(a -> assertThat(a.getApiKey()).as("check apiKey").isEqualTo(expected.getApiKey()))
            .satisfies(a -> assertThat(a.getTimeout()).as("check timeout").isEqualTo(expected.getTimeout()))
            .satisfies(a -> assertThat(a.getMaxFileSize()).as("check maxFileSize").isEqualTo(expected.getMaxFileSize()))
            .satisfies(a -> assertThat(a.getSupportedLanguages()).as("check supportedLanguages").isEqualTo(expected.getSupportedLanguages())
            )
            .satisfies(a -> assertThat(a.getEnableOcr()).as("check enableOcr").isEqualTo(expected.getEnableOcr()))
            .satisfies(a -> assertThat(a.getOcrEngine()).as("check ocrEngine").isEqualTo(expected.getOcrEngine()))
            .satisfies(a -> assertThat(a.getIsDefault()).as("check isDefault").isEqualTo(expected.getIsDefault()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTikaConfigurationUpdatableRelationshipsEquals(TikaConfiguration expected, TikaConfiguration actual) {
        // empty method
    }
}
