package fr.smartprod.paperdms.pdftoimage.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImageGeneratedImageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageGeneratedImageAllPropertiesEquals(ImageGeneratedImage expected, ImageGeneratedImage actual) {
        assertImageGeneratedImageAutoGeneratedPropertiesEquals(expected, actual);
        assertImageGeneratedImageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageGeneratedImageAllUpdatablePropertiesEquals(ImageGeneratedImage expected, ImageGeneratedImage actual) {
        assertImageGeneratedImageUpdatableFieldsEquals(expected, actual);
        assertImageGeneratedImageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageGeneratedImageAutoGeneratedPropertiesEquals(ImageGeneratedImage expected, ImageGeneratedImage actual) {
        assertThat(actual)
            .as("Verify ImageGeneratedImage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageGeneratedImageUpdatableFieldsEquals(ImageGeneratedImage expected, ImageGeneratedImage actual) {
        assertThat(actual)
            .as("Verify ImageGeneratedImage relevant properties")
            .satisfies(a -> assertThat(a.getPageNumber()).as("check pageNumber").isEqualTo(expected.getPageNumber()))
            .satisfies(a -> assertThat(a.getFileName()).as("check fileName").isEqualTo(expected.getFileName()))
            .satisfies(a -> assertThat(a.gets3Key()).as("check s3Key").isEqualTo(expected.gets3Key()))
            .satisfies(a -> assertThat(a.getPreSignedUrl()).as("check preSignedUrl").isEqualTo(expected.getPreSignedUrl()))
            .satisfies(a -> assertThat(a.getUrlExpiresAt()).as("check urlExpiresAt").isEqualTo(expected.getUrlExpiresAt()))
            .satisfies(a -> assertThat(a.getFormat()).as("check format").isEqualTo(expected.getFormat()))
            .satisfies(a -> assertThat(a.getQuality()).as("check quality").isEqualTo(expected.getQuality()))
            .satisfies(a -> assertThat(a.getWidth()).as("check width").isEqualTo(expected.getWidth()))
            .satisfies(a -> assertThat(a.getHeight()).as("check height").isEqualTo(expected.getHeight()))
            .satisfies(a -> assertThat(a.getFileSize()).as("check fileSize").isEqualTo(expected.getFileSize()))
            .satisfies(a -> assertThat(a.getDpi()).as("check dpi").isEqualTo(expected.getDpi()))
            .satisfies(a -> assertThat(a.getSha256Hash()).as("check sha256Hash").isEqualTo(expected.getSha256Hash()))
            .satisfies(a -> assertThat(a.getGeneratedAt()).as("check generatedAt").isEqualTo(expected.getGeneratedAt()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageGeneratedImageUpdatableRelationshipsEquals(ImageGeneratedImage expected, ImageGeneratedImage actual) {
        assertThat(actual)
            .as("Verify ImageGeneratedImage relationships")
            .satisfies(a -> assertThat(a.getConversionRequest()).as("check conversionRequest").isEqualTo(expected.getConversionRequest()));
    }
}
