package fr.smartprod.paperdms.pdftoimage.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImageConversionConfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionConfigAllPropertiesEquals(ImageConversionConfig expected, ImageConversionConfig actual) {
        assertImageConversionConfigAutoGeneratedPropertiesEquals(expected, actual);
        assertImageConversionConfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionConfigAllUpdatablePropertiesEquals(
        ImageConversionConfig expected,
        ImageConversionConfig actual
    ) {
        assertImageConversionConfigUpdatableFieldsEquals(expected, actual);
        assertImageConversionConfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionConfigAutoGeneratedPropertiesEquals(
        ImageConversionConfig expected,
        ImageConversionConfig actual
    ) {
        assertThat(actual)
            .as("Verify ImageConversionConfig auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionConfigUpdatableFieldsEquals(ImageConversionConfig expected, ImageConversionConfig actual) {
        assertThat(actual)
            .as("Verify ImageConversionConfig relevant properties")
            .satisfies(a -> assertThat(a.getConfigName()).as("check configName").isEqualTo(expected.getConfigName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getDefaultQuality()).as("check defaultQuality").isEqualTo(expected.getDefaultQuality()))
            .satisfies(a -> assertThat(a.getDefaultFormat()).as("check defaultFormat").isEqualTo(expected.getDefaultFormat()))
            .satisfies(a -> assertThat(a.getDefaultDpi()).as("check defaultDpi").isEqualTo(expected.getDefaultDpi()))
            .satisfies(a ->
                assertThat(a.getDefaultConversionType()).as("check defaultConversionType").isEqualTo(expected.getDefaultConversionType())
            )
            .satisfies(a -> assertThat(a.getDefaultPriority()).as("check defaultPriority").isEqualTo(expected.getDefaultPriority()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getIsDefault()).as("check isDefault").isEqualTo(expected.getIsDefault()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionConfigUpdatableRelationshipsEquals(
        ImageConversionConfig expected,
        ImageConversionConfig actual
    ) {
        // empty method
    }
}
