package fr.smartprod.paperdms.pdftoimage.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImageConversionHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionHistoryAllPropertiesEquals(ImageConversionHistory expected, ImageConversionHistory actual) {
        assertImageConversionHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertImageConversionHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionHistoryAllUpdatablePropertiesEquals(
        ImageConversionHistory expected,
        ImageConversionHistory actual
    ) {
        assertImageConversionHistoryUpdatableFieldsEquals(expected, actual);
        assertImageConversionHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionHistoryAutoGeneratedPropertiesEquals(
        ImageConversionHistory expected,
        ImageConversionHistory actual
    ) {
        assertThat(actual)
            .as("Verify ImageConversionHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionHistoryUpdatableFieldsEquals(ImageConversionHistory expected, ImageConversionHistory actual) {
        assertThat(actual)
            .as("Verify ImageConversionHistory relevant properties")
            .satisfies(a -> assertThat(a.getOriginalRequestId()).as("check originalRequestId").isEqualTo(expected.getOriginalRequestId()))
            .satisfies(a -> assertThat(a.getArchivedAt()).as("check archivedAt").isEqualTo(expected.getArchivedAt()))
            .satisfies(a -> assertThat(a.getConversionData()).as("check conversionData").isEqualTo(expected.getConversionData()))
            .satisfies(a -> assertThat(a.getImagesCount()).as("check imagesCount").isEqualTo(expected.getImagesCount()))
            .satisfies(a -> assertThat(a.getTotalSize()).as("check totalSize").isEqualTo(expected.getTotalSize()))
            .satisfies(a -> assertThat(a.getFinalStatus()).as("check finalStatus").isEqualTo(expected.getFinalStatus()))
            .satisfies(a -> assertThat(a.getProcessingDuration()).as("check processingDuration").isEqualTo(expected.getProcessingDuration())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionHistoryUpdatableRelationshipsEquals(
        ImageConversionHistory expected,
        ImageConversionHistory actual
    ) {
        // empty method
    }
}
