package fr.smartprod.paperdms.pdftoimage.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImagePdfConversionRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImagePdfConversionRequestAllPropertiesEquals(
        ImagePdfConversionRequest expected,
        ImagePdfConversionRequest actual
    ) {
        assertImagePdfConversionRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertImagePdfConversionRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImagePdfConversionRequestAllUpdatablePropertiesEquals(
        ImagePdfConversionRequest expected,
        ImagePdfConversionRequest actual
    ) {
        assertImagePdfConversionRequestUpdatableFieldsEquals(expected, actual);
        assertImagePdfConversionRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImagePdfConversionRequestAutoGeneratedPropertiesEquals(
        ImagePdfConversionRequest expected,
        ImagePdfConversionRequest actual
    ) {
        assertThat(actual)
            .as("Verify ImagePdfConversionRequest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImagePdfConversionRequestUpdatableFieldsEquals(
        ImagePdfConversionRequest expected,
        ImagePdfConversionRequest actual
    ) {
        assertThat(actual)
            .as("Verify ImagePdfConversionRequest relevant properties")
            .satisfies(a -> assertThat(a.getSourceDocumentId()).as("check sourceDocumentId").isEqualTo(expected.getSourceDocumentId()))
            .satisfies(a -> assertThat(a.getSourceFileName()).as("check sourceFileName").isEqualTo(expected.getSourceFileName()))
            .satisfies(a -> assertThat(a.getSourcePdfS3Key()).as("check sourcePdfS3Key").isEqualTo(expected.getSourcePdfS3Key()))
            .satisfies(a -> assertThat(a.getImageQuality()).as("check imageQuality").isEqualTo(expected.getImageQuality()))
            .satisfies(a -> assertThat(a.getImageFormat()).as("check imageFormat").isEqualTo(expected.getImageFormat()))
            .satisfies(a -> assertThat(a.getConversionType()).as("check conversionType").isEqualTo(expected.getConversionType()))
            .satisfies(a -> assertThat(a.getStartPage()).as("check startPage").isEqualTo(expected.getStartPage()))
            .satisfies(a -> assertThat(a.getEndPage()).as("check endPage").isEqualTo(expected.getEndPage()))
            .satisfies(a -> assertThat(a.getTotalPages()).as("check totalPages").isEqualTo(expected.getTotalPages()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getRequestedAt()).as("check requestedAt").isEqualTo(expected.getRequestedAt()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getCompletedAt()).as("check completedAt").isEqualTo(expected.getCompletedAt()))
            .satisfies(a -> assertThat(a.getProcessingDuration()).as("check processingDuration").isEqualTo(expected.getProcessingDuration())
            )
            .satisfies(a -> assertThat(a.getTotalImagesSize()).as("check totalImagesSize").isEqualTo(expected.getTotalImagesSize()))
            .satisfies(a -> assertThat(a.getImagesGenerated()).as("check imagesGenerated").isEqualTo(expected.getImagesGenerated()))
            .satisfies(a -> assertThat(a.getDpi()).as("check dpi").isEqualTo(expected.getDpi()))
            .satisfies(a -> assertThat(a.getRequestedByUserId()).as("check requestedByUserId").isEqualTo(expected.getRequestedByUserId()))
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()))
            .satisfies(a -> assertThat(a.getAdditionalOptions()).as("check additionalOptions").isEqualTo(expected.getAdditionalOptions()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImagePdfConversionRequestUpdatableRelationshipsEquals(
        ImagePdfConversionRequest expected,
        ImagePdfConversionRequest actual
    ) {
        assertThat(actual)
            .as("Verify ImagePdfConversionRequest relationships")
            .satisfies(a -> assertThat(a.getBatch()).as("check batch").isEqualTo(expected.getBatch()));
    }
}
