package com.ged.search.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SearchQueryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchQueryAllPropertiesEquals(SearchQuery expected, SearchQuery actual) {
        assertSearchQueryAutoGeneratedPropertiesEquals(expected, actual);
        assertSearchQueryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchQueryAllUpdatablePropertiesEquals(SearchQuery expected, SearchQuery actual) {
        assertSearchQueryUpdatableFieldsEquals(expected, actual);
        assertSearchQueryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchQueryAutoGeneratedPropertiesEquals(SearchQuery expected, SearchQuery actual) {
        assertThat(actual)
            .as("Verify SearchQuery auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchQueryUpdatableFieldsEquals(SearchQuery expected, SearchQuery actual) {
        assertThat(actual)
            .as("Verify SearchQuery relevant properties")
            .satisfies(a -> assertThat(a.getQuery()).as("check query").isEqualTo(expected.getQuery()))
            .satisfies(a -> assertThat(a.getFilters()).as("check filters").isEqualTo(expected.getFilters()))
            .satisfies(a -> assertThat(a.getResultCount()).as("check resultCount").isEqualTo(expected.getResultCount()))
            .satisfies(a -> assertThat(a.getExecutionTime()).as("check executionTime").isEqualTo(expected.getExecutionTime()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getSearchDate()).as("check searchDate").isEqualTo(expected.getSearchDate()))
            .satisfies(a -> assertThat(a.getIsRelevant()).as("check isRelevant").isEqualTo(expected.getIsRelevant()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchQueryUpdatableRelationshipsEquals(SearchQuery expected, SearchQuery actual) {
        // empty method
    }
}
