package com.ged.ai.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AutoTagJobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutoTagJobAllPropertiesEquals(AutoTagJob expected, AutoTagJob actual) {
        assertAutoTagJobAutoGeneratedPropertiesEquals(expected, actual);
        assertAutoTagJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutoTagJobAllUpdatablePropertiesEquals(AutoTagJob expected, AutoTagJob actual) {
        assertAutoTagJobUpdatableFieldsEquals(expected, actual);
        assertAutoTagJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutoTagJobAutoGeneratedPropertiesEquals(AutoTagJob expected, AutoTagJob actual) {
        assertThat(actual)
            .as("Verify AutoTagJob auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutoTagJobUpdatableFieldsEquals(AutoTagJob expected, AutoTagJob actual) {
        assertThat(actual)
            .as("Verify AutoTagJob relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.gets3Key()).as("check s3Key").isEqualTo(expected.gets3Key()))
            .satisfies(a -> assertThat(a.getExtractedText()).as("check extractedText").isEqualTo(expected.getExtractedText()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getModelVersion()).as("check modelVersion").isEqualTo(expected.getModelVersion()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutoTagJobUpdatableRelationshipsEquals(AutoTagJob expected, AutoTagJob actual) {
        // empty method
    }
}
