package com.ged.ai.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CorrespondentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorrespondentAllPropertiesEquals(Correspondent expected, Correspondent actual) {
        assertCorrespondentAutoGeneratedPropertiesEquals(expected, actual);
        assertCorrespondentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorrespondentAllUpdatablePropertiesEquals(Correspondent expected, Correspondent actual) {
        assertCorrespondentUpdatableFieldsEquals(expected, actual);
        assertCorrespondentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorrespondentAutoGeneratedPropertiesEquals(Correspondent expected, Correspondent actual) {
        assertThat(actual)
            .as("Verify Correspondent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorrespondentUpdatableFieldsEquals(Correspondent expected, Correspondent actual) {
        assertThat(actual)
            .as("Verify Correspondent relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.getIsVerified()).as("check isVerified").isEqualTo(expected.getIsVerified()))
            .satisfies(a -> assertThat(a.getVerifiedBy()).as("check verifiedBy").isEqualTo(expected.getVerifiedBy()))
            .satisfies(a -> assertThat(a.getVerifiedDate()).as("check verifiedDate").isEqualTo(expected.getVerifiedDate()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()))
            .satisfies(a -> assertThat(a.getExtractedDate()).as("check extractedDate").isEqualTo(expected.getExtractedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorrespondentUpdatableRelationshipsEquals(Correspondent expected, Correspondent actual) {
        assertThat(actual)
            .as("Verify Correspondent relationships")
            .satisfies(a -> assertThat(a.getExtraction()).as("check extraction").isEqualTo(expected.getExtraction()));
    }
}
