package fr.smartprod.paperdms.search.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SearchSemanticAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchSemanticAllPropertiesEquals(SearchSemantic expected, SearchSemantic actual) {
        assertSearchSemanticAutoGeneratedPropertiesEquals(expected, actual);
        assertSearchSemanticAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchSemanticAllUpdatablePropertiesEquals(SearchSemantic expected, SearchSemantic actual) {
        assertSearchSemanticUpdatableFieldsEquals(expected, actual);
        assertSearchSemanticUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchSemanticAutoGeneratedPropertiesEquals(SearchSemantic expected, SearchSemantic actual) {
        assertThat(actual)
            .as("Verify SearchSemantic auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchSemanticUpdatableFieldsEquals(SearchSemantic expected, SearchSemantic actual) {
        assertThat(actual)
            .as("Verify SearchSemantic relevant properties")
            .satisfies(a -> assertThat(a.getQuery()).as("check query").isEqualTo(expected.getQuery()))
            .satisfies(a -> assertThat(a.getQueryEmbedding()).as("check queryEmbedding").isEqualTo(expected.getQueryEmbedding()))
            .satisfies(a -> assertThat(a.getResults()).as("check results").isEqualTo(expected.getResults()))
            .satisfies(a -> assertThat(a.getRelevanceScores()).as("check relevanceScores").isEqualTo(expected.getRelevanceScores()))
            .satisfies(a -> assertThat(a.getModelUsed()).as("check modelUsed").isEqualTo(expected.getModelUsed()))
            .satisfies(a -> assertThat(a.getExecutionTime()).as("check executionTime").isEqualTo(expected.getExecutionTime()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getSearchDate()).as("check searchDate").isEqualTo(expected.getSearchDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchSemanticUpdatableRelationshipsEquals(SearchSemantic expected, SearchSemantic actual) {
        // empty method
    }
}
