package fr.smartprod.paperdms.workflow.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApprovalHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApprovalHistoryAllPropertiesEquals(ApprovalHistory expected, ApprovalHistory actual) {
        assertApprovalHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertApprovalHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApprovalHistoryAllUpdatablePropertiesEquals(ApprovalHistory expected, ApprovalHistory actual) {
        assertApprovalHistoryUpdatableFieldsEquals(expected, actual);
        assertApprovalHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApprovalHistoryAutoGeneratedPropertiesEquals(ApprovalHistory expected, ApprovalHistory actual) {
        assertThat(actual)
            .as("Verify ApprovalHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApprovalHistoryUpdatableFieldsEquals(ApprovalHistory expected, ApprovalHistory actual) {
        assertThat(actual)
            .as("Verify ApprovalHistory relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a ->
                assertThat(a.getWorkflowInstanceId()).as("check workflowInstanceId").isEqualTo(expected.getWorkflowInstanceId())
            )
            .satisfies(a -> assertThat(a.getStepNumber()).as("check stepNumber").isEqualTo(expected.getStepNumber()))
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getComment()).as("check comment").isEqualTo(expected.getComment()))
            .satisfies(a -> assertThat(a.getActionDate()).as("check actionDate").isEqualTo(expected.getActionDate()))
            .satisfies(a -> assertThat(a.getActionBy()).as("check actionBy").isEqualTo(expected.getActionBy()))
            .satisfies(a -> assertThat(a.getPreviousAssignee()).as("check previousAssignee").isEqualTo(expected.getPreviousAssignee()))
            .satisfies(a -> assertThat(a.getTimeTaken()).as("check timeTaken").isEqualTo(expected.getTimeTaken()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApprovalHistoryUpdatableRelationshipsEquals(ApprovalHistory expected, ApprovalHistory actual) {
        // empty method
    }
}
