package fr.smartprod.paperdms.workflow.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WorkflowAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowAllPropertiesEquals(Workflow expected, Workflow actual) {
        assertWorkflowAutoGeneratedPropertiesEquals(expected, actual);
        assertWorkflowAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowAllUpdatablePropertiesEquals(Workflow expected, Workflow actual) {
        assertWorkflowUpdatableFieldsEquals(expected, actual);
        assertWorkflowUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowAutoGeneratedPropertiesEquals(Workflow expected, Workflow actual) {
        assertThat(actual)
            .as("Verify Workflow auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowUpdatableFieldsEquals(Workflow expected, Workflow actual) {
        assertThat(actual)
            .as("Verify Workflow relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getVersion()).as("check version").isEqualTo(expected.getVersion()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getIsParallel()).as("check isParallel").isEqualTo(expected.getIsParallel()))
            .satisfies(a -> assertThat(a.getAutoStart()).as("check autoStart").isEqualTo(expected.getAutoStart()))
            .satisfies(a -> assertThat(a.getTriggerEvent()).as("check triggerEvent").isEqualTo(expected.getTriggerEvent()))
            .satisfies(a -> assertThat(a.getConfiguration()).as("check configuration").isEqualTo(expected.getConfiguration()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowUpdatableRelationshipsEquals(Workflow expected, Workflow actual) {
        // empty method
    }
}
