package fr.smartprod.paperdms.workflow.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WorkflowApprovalHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowApprovalHistoryAllPropertiesEquals(WorkflowApprovalHistory expected, WorkflowApprovalHistory actual) {
        assertWorkflowApprovalHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertWorkflowApprovalHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowApprovalHistoryAllUpdatablePropertiesEquals(
        WorkflowApprovalHistory expected,
        WorkflowApprovalHistory actual
    ) {
        assertWorkflowApprovalHistoryUpdatableFieldsEquals(expected, actual);
        assertWorkflowApprovalHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowApprovalHistoryAutoGeneratedPropertiesEquals(
        WorkflowApprovalHistory expected,
        WorkflowApprovalHistory actual
    ) {
        assertThat(actual)
            .as("Verify WorkflowApprovalHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowApprovalHistoryUpdatableFieldsEquals(
        WorkflowApprovalHistory expected,
        WorkflowApprovalHistory actual
    ) {
        assertThat(actual)
            .as("Verify WorkflowApprovalHistory relevant properties")
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()))
            .satisfies(a -> assertThat(a.getStepNumber()).as("check stepNumber").isEqualTo(expected.getStepNumber()))
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getComment()).as("check comment").isEqualTo(expected.getComment()))
            .satisfies(a -> assertThat(a.getActionDate()).as("check actionDate").isEqualTo(expected.getActionDate()))
            .satisfies(a -> assertThat(a.getActionBy()).as("check actionBy").isEqualTo(expected.getActionBy()))
            .satisfies(a -> assertThat(a.getPreviousAssignee()).as("check previousAssignee").isEqualTo(expected.getPreviousAssignee()))
            .satisfies(a -> assertThat(a.getTimeTaken()).as("check timeTaken").isEqualTo(expected.getTimeTaken()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowApprovalHistoryUpdatableRelationshipsEquals(
        WorkflowApprovalHistory expected,
        WorkflowApprovalHistory actual
    ) {
        assertThat(actual)
            .as("Verify WorkflowApprovalHistory relationships")
            .satisfies(a -> assertThat(a.getWorkflowInstance()).as("check workflowInstance").isEqualTo(expected.getWorkflowInstance()));
    }
}
