package fr.smartprod.paperdms.workflow.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WorkflowInstanceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowInstanceAllPropertiesEquals(WorkflowInstance expected, WorkflowInstance actual) {
        assertWorkflowInstanceAutoGeneratedPropertiesEquals(expected, actual);
        assertWorkflowInstanceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowInstanceAllUpdatablePropertiesEquals(WorkflowInstance expected, WorkflowInstance actual) {
        assertWorkflowInstanceUpdatableFieldsEquals(expected, actual);
        assertWorkflowInstanceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowInstanceAutoGeneratedPropertiesEquals(WorkflowInstance expected, WorkflowInstance actual) {
        assertThat(actual)
            .as("Verify WorkflowInstance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowInstanceUpdatableFieldsEquals(WorkflowInstance expected, WorkflowInstance actual) {
        assertThat(actual)
            .as("Verify WorkflowInstance relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCurrentStepNumber()).as("check currentStepNumber").isEqualTo(expected.getCurrentStepNumber()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getDueDate()).as("check dueDate").isEqualTo(expected.getDueDate()))
            .satisfies(a -> assertThat(a.getCompletedDate()).as("check completedDate").isEqualTo(expected.getCompletedDate()))
            .satisfies(a -> assertThat(a.getCancelledDate()).as("check cancelledDate").isEqualTo(expected.getCancelledDate()))
            .satisfies(a ->
                assertThat(a.getCancellationReason()).as("check cancellationReason").isEqualTo(expected.getCancellationReason())
            )
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowInstanceUpdatableRelationshipsEquals(WorkflowInstance expected, WorkflowInstance actual) {
        assertThat(actual)
            .as("Verify WorkflowInstance relationships")
            .satisfies(a -> assertThat(a.getWorkflow()).as("check workflow").isEqualTo(expected.getWorkflow()));
    }
}
