package fr.smartprod.paperdms.export.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExportPatternAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportPatternAllPropertiesEquals(ExportPattern expected, ExportPattern actual) {
        assertExportPatternAutoGeneratedPropertiesEquals(expected, actual);
        assertExportPatternAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportPatternAllUpdatablePropertiesEquals(ExportPattern expected, ExportPattern actual) {
        assertExportPatternUpdatableFieldsEquals(expected, actual);
        assertExportPatternUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportPatternAutoGeneratedPropertiesEquals(ExportPattern expected, ExportPattern actual) {
        assertThat(actual)
            .as("Verify ExportPattern auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportPatternUpdatableFieldsEquals(ExportPattern expected, ExportPattern actual) {
        assertThat(actual)
            .as("Verify ExportPattern relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPathTemplate()).as("check pathTemplate").isEqualTo(expected.getPathTemplate()))
            .satisfies(a -> assertThat(a.getFileNameTemplate()).as("check fileNameTemplate").isEqualTo(expected.getFileNameTemplate()))
            .satisfies(a -> assertThat(a.getVariables()).as("check variables").isEqualTo(expected.getVariables()))
            .satisfies(a -> assertThat(a.getExamples()).as("check examples").isEqualTo(expected.getExamples()))
            .satisfies(a -> assertThat(a.getIsSystem()).as("check isSystem").isEqualTo(expected.getIsSystem()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getUsageCount()).as("check usageCount").isEqualTo(expected.getUsageCount()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportPatternUpdatableRelationshipsEquals(ExportPattern expected, ExportPattern actual) {
        // empty method
    }
}
