package fr.smartprod.paperdms.monitoring.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MonitoringSystemHealthAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringSystemHealthAllPropertiesEquals(MonitoringSystemHealth expected, MonitoringSystemHealth actual) {
        assertMonitoringSystemHealthAutoGeneratedPropertiesEquals(expected, actual);
        assertMonitoringSystemHealthAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringSystemHealthAllUpdatablePropertiesEquals(
        MonitoringSystemHealth expected,
        MonitoringSystemHealth actual
    ) {
        assertMonitoringSystemHealthUpdatableFieldsEquals(expected, actual);
        assertMonitoringSystemHealthUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringSystemHealthAutoGeneratedPropertiesEquals(
        MonitoringSystemHealth expected,
        MonitoringSystemHealth actual
    ) {
        assertThat(actual)
            .as("Verify MonitoringSystemHealth auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringSystemHealthUpdatableFieldsEquals(MonitoringSystemHealth expected, MonitoringSystemHealth actual) {
        assertThat(actual)
            .as("Verify MonitoringSystemHealth relevant properties")
            .satisfies(a -> assertThat(a.getServiceName()).as("check serviceName").isEqualTo(expected.getServiceName()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getVersion()).as("check version").isEqualTo(expected.getVersion()))
            .satisfies(a -> assertThat(a.getUptime()).as("check uptime").isEqualTo(expected.getUptime()))
            .satisfies(a -> assertThat(a.getCpuUsage()).as("check cpuUsage").isEqualTo(expected.getCpuUsage()))
            .satisfies(a -> assertThat(a.getMemoryUsage()).as("check memoryUsage").isEqualTo(expected.getMemoryUsage()))
            .satisfies(a -> assertThat(a.getErrorRate()).as("check errorRate").isEqualTo(expected.getErrorRate()))
            .satisfies(a -> assertThat(a.getLastCheck()).as("check lastCheck").isEqualTo(expected.getLastCheck()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringSystemHealthUpdatableRelationshipsEquals(
        MonitoringSystemHealth expected,
        MonitoringSystemHealth actual
    ) {
        // empty method
    }
}
