package fr.smartprod.paperdms.monitoring.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MonitoringAlertRuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringAlertRuleAllPropertiesEquals(MonitoringAlertRule expected, MonitoringAlertRule actual) {
        assertMonitoringAlertRuleAutoGeneratedPropertiesEquals(expected, actual);
        assertMonitoringAlertRuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringAlertRuleAllUpdatablePropertiesEquals(MonitoringAlertRule expected, MonitoringAlertRule actual) {
        assertMonitoringAlertRuleUpdatableFieldsEquals(expected, actual);
        assertMonitoringAlertRuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringAlertRuleAutoGeneratedPropertiesEquals(MonitoringAlertRule expected, MonitoringAlertRule actual) {
        assertThat(actual)
            .as("Verify MonitoringAlertRule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringAlertRuleUpdatableFieldsEquals(MonitoringAlertRule expected, MonitoringAlertRule actual) {
        assertThat(actual)
            .as("Verify MonitoringAlertRule relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getAlertType()).as("check alertType").isEqualTo(expected.getAlertType()))
            .satisfies(a -> assertThat(a.getConditions()).as("check conditions").isEqualTo(expected.getConditions()))
            .satisfies(a -> assertThat(a.getSeverity()).as("check severity").isEqualTo(expected.getSeverity()))
            .satisfies(a -> assertThat(a.getRecipients()).as("check recipients").isEqualTo(expected.getRecipients()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getTriggerCount()).as("check triggerCount").isEqualTo(expected.getTriggerCount()))
            .satisfies(a -> assertThat(a.getLastTriggered()).as("check lastTriggered").isEqualTo(expected.getLastTriggered()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitoringAlertRuleUpdatableRelationshipsEquals(MonitoringAlertRule expected, MonitoringAlertRule actual) {
        // empty method
    }
}
