package fr.smartprod.paperdms.notification.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificationEventAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationEventAllPropertiesEquals(NotificationEvent expected, NotificationEvent actual) {
        assertNotificationEventAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationEventAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationEventAllUpdatablePropertiesEquals(NotificationEvent expected, NotificationEvent actual) {
        assertNotificationEventUpdatableFieldsEquals(expected, actual);
        assertNotificationEventUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationEventAutoGeneratedPropertiesEquals(NotificationEvent expected, NotificationEvent actual) {
        assertThat(actual)
            .as("Verify NotificationEvent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationEventUpdatableFieldsEquals(NotificationEvent expected, NotificationEvent actual) {
        assertThat(actual)
            .as("Verify NotificationEvent relevant properties")
            .satisfies(a -> assertThat(a.getEventType()).as("check eventType").isEqualTo(expected.getEventType()))
            .satisfies(a -> assertThat(a.getEntityType()).as("check entityType").isEqualTo(expected.getEntityType()))
            .satisfies(a -> assertThat(a.getEntityId()).as("check entityId").isEqualTo(expected.getEntityId()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getEventData()).as("check eventData").isEqualTo(expected.getEventData()))
            .satisfies(a -> assertThat(a.getEventDate()).as("check eventDate").isEqualTo(expected.getEventDate()))
            .satisfies(a -> assertThat(a.getProcessed()).as("check processed").isEqualTo(expected.getProcessed()))
            .satisfies(a -> assertThat(a.getProcessedDate()).as("check processedDate").isEqualTo(expected.getProcessedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationEventUpdatableRelationshipsEquals(NotificationEvent expected, NotificationEvent actual) {
        // empty method
    }
}
