package fr.smartprod.paperdms.notification.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotificationWebhookLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationWebhookLogAllPropertiesEquals(NotificationWebhookLog expected, NotificationWebhookLog actual) {
        assertNotificationWebhookLogAutoGeneratedPropertiesEquals(expected, actual);
        assertNotificationWebhookLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationWebhookLogAllUpdatablePropertiesEquals(
        NotificationWebhookLog expected,
        NotificationWebhookLog actual
    ) {
        assertNotificationWebhookLogUpdatableFieldsEquals(expected, actual);
        assertNotificationWebhookLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationWebhookLogAutoGeneratedPropertiesEquals(
        NotificationWebhookLog expected,
        NotificationWebhookLog actual
    ) {
        assertThat(actual)
            .as("Verify NotificationWebhookLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationWebhookLogUpdatableFieldsEquals(NotificationWebhookLog expected, NotificationWebhookLog actual) {
        assertThat(actual)
            .as("Verify NotificationWebhookLog relevant properties")
            .satisfies(a -> assertThat(a.getEventType()).as("check eventType").isEqualTo(expected.getEventType()))
            .satisfies(a -> assertThat(a.getPayload()).as("check payload").isEqualTo(expected.getPayload()))
            .satisfies(a -> assertThat(a.getResponseStatus()).as("check responseStatus").isEqualTo(expected.getResponseStatus()))
            .satisfies(a -> assertThat(a.getResponseBody()).as("check responseBody").isEqualTo(expected.getResponseBody()))
            .satisfies(a -> assertThat(a.getResponseTime()).as("check responseTime").isEqualTo(expected.getResponseTime()))
            .satisfies(a -> assertThat(a.getAttemptNumber()).as("check attemptNumber").isEqualTo(expected.getAttemptNumber()))
            .satisfies(a -> assertThat(a.getIsSuccess()).as("check isSuccess").isEqualTo(expected.getIsSuccess()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getSentDate()).as("check sentDate").isEqualTo(expected.getSentDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotificationWebhookLogUpdatableRelationshipsEquals(
        NotificationWebhookLog expected,
        NotificationWebhookLog actual
    ) {
        assertThat(actual)
            .as("Verify NotificationWebhookLog relationships")
            .satisfies(a -> assertThat(a.getSubscription()).as("check subscription").isEqualTo(expected.getSubscription()));
    }
}
