package fr.smartprod.paperdms.notification.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WebhookLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookLogAllPropertiesEquals(WebhookLog expected, WebhookLog actual) {
        assertWebhookLogAutoGeneratedPropertiesEquals(expected, actual);
        assertWebhookLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookLogAllUpdatablePropertiesEquals(WebhookLog expected, WebhookLog actual) {
        assertWebhookLogUpdatableFieldsEquals(expected, actual);
        assertWebhookLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookLogAutoGeneratedPropertiesEquals(WebhookLog expected, WebhookLog actual) {
        assertThat(actual)
            .as("Verify WebhookLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookLogUpdatableFieldsEquals(WebhookLog expected, WebhookLog actual) {
        assertThat(actual)
            .as("Verify WebhookLog relevant properties")
            .satisfies(a -> assertThat(a.getSubscriptionId()).as("check subscriptionId").isEqualTo(expected.getSubscriptionId()))
            .satisfies(a -> assertThat(a.getEventType()).as("check eventType").isEqualTo(expected.getEventType()))
            .satisfies(a -> assertThat(a.getPayload()).as("check payload").isEqualTo(expected.getPayload()))
            .satisfies(a -> assertThat(a.getResponseStatus()).as("check responseStatus").isEqualTo(expected.getResponseStatus()))
            .satisfies(a -> assertThat(a.getResponseBody()).as("check responseBody").isEqualTo(expected.getResponseBody()))
            .satisfies(a -> assertThat(a.getResponseTime()).as("check responseTime").isEqualTo(expected.getResponseTime()))
            .satisfies(a -> assertThat(a.getAttemptNumber()).as("check attemptNumber").isEqualTo(expected.getAttemptNumber()))
            .satisfies(a -> assertThat(a.getIsSuccess()).as("check isSuccess").isEqualTo(expected.getIsSuccess()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getSentDate()).as("check sentDate").isEqualTo(expected.getSentDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookLogUpdatableRelationshipsEquals(WebhookLog expected, WebhookLog actual) {
        assertThat(actual)
            .as("Verify WebhookLog relationships")
            .satisfies(a -> assertThat(a.getSubscription()).as("check subscription").isEqualTo(expected.getSubscription()));
    }
}
