package fr.smartprod.paperdms.notification.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WebhookSubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookSubscriptionAllPropertiesEquals(WebhookSubscription expected, WebhookSubscription actual) {
        assertWebhookSubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertWebhookSubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookSubscriptionAllUpdatablePropertiesEquals(WebhookSubscription expected, WebhookSubscription actual) {
        assertWebhookSubscriptionUpdatableFieldsEquals(expected, actual);
        assertWebhookSubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookSubscriptionAutoGeneratedPropertiesEquals(WebhookSubscription expected, WebhookSubscription actual) {
        assertThat(actual)
            .as("Verify WebhookSubscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookSubscriptionUpdatableFieldsEquals(WebhookSubscription expected, WebhookSubscription actual) {
        assertThat(actual)
            .as("Verify WebhookSubscription relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getSecret()).as("check secret").isEqualTo(expected.getSecret()))
            .satisfies(a -> assertThat(a.getEvents()).as("check events").isEqualTo(expected.getEvents()))
            .satisfies(a -> assertThat(a.getHeaders()).as("check headers").isEqualTo(expected.getHeaders()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getRetryCount()).as("check retryCount").isEqualTo(expected.getRetryCount()))
            .satisfies(a -> assertThat(a.getMaxRetries()).as("check maxRetries").isEqualTo(expected.getMaxRetries()))
            .satisfies(a -> assertThat(a.getRetryDelay()).as("check retryDelay").isEqualTo(expected.getRetryDelay()))
            .satisfies(a -> assertThat(a.getLastTriggerDate()).as("check lastTriggerDate").isEqualTo(expected.getLastTriggerDate()))
            .satisfies(a -> assertThat(a.getLastSuccessDate()).as("check lastSuccessDate").isEqualTo(expected.getLastSuccessDate()))
            .satisfies(a -> assertThat(a.getLastErrorMessage()).as("check lastErrorMessage").isEqualTo(expected.getLastErrorMessage()))
            .satisfies(a -> assertThat(a.getFailureCount()).as("check failureCount").isEqualTo(expected.getFailureCount()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookSubscriptionUpdatableRelationshipsEquals(WebhookSubscription expected, WebhookSubscription actual) {
        // empty method
    }
}
