package fr.smartprod.paperdms.emailimportdocument.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmailImportDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportDocumentAllPropertiesEquals(EmailImportDocument expected, EmailImportDocument actual) {
        assertEmailImportDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertEmailImportDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportDocumentAllUpdatablePropertiesEquals(EmailImportDocument expected, EmailImportDocument actual) {
        assertEmailImportDocumentUpdatableFieldsEquals(expected, actual);
        assertEmailImportDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportDocumentAutoGeneratedPropertiesEquals(EmailImportDocument expected, EmailImportDocument actual) {
        assertThat(actual)
            .as("Verify EmailImportDocument auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportDocumentUpdatableFieldsEquals(EmailImportDocument expected, EmailImportDocument actual) {
        assertThat(actual)
            .as("Verify EmailImportDocument relevant properties")
            .satisfies(a -> assertThat(a.getSha256()).as("check sha256").isEqualTo(expected.getSha256()))
            .satisfies(a -> assertThat(a.getFromEmail()).as("check fromEmail").isEqualTo(expected.getFromEmail()))
            .satisfies(a -> assertThat(a.getToEmail()).as("check toEmail").isEqualTo(expected.getToEmail()))
            .satisfies(a -> assertThat(a.getSubject()).as("check subject").isEqualTo(expected.getSubject()))
            .satisfies(a -> assertThat(a.getBody()).as("check body").isEqualTo(expected.getBody()))
            .satisfies(a -> assertThat(a.getBodyHtml()).as("check bodyHtml").isEqualTo(expected.getBodyHtml()))
            .satisfies(a -> assertThat(a.getReceivedDate()).as("check receivedDate").isEqualTo(expected.getReceivedDate()))
            .satisfies(a -> assertThat(a.getProcessedDate()).as("check processedDate").isEqualTo(expected.getProcessedDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getAttachmentCount()).as("check attachmentCount").isEqualTo(expected.getAttachmentCount()))
            .satisfies(a -> assertThat(a.getDocumentsCreated()).as("check documentsCreated").isEqualTo(expected.getDocumentsCreated()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()))
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportDocumentUpdatableRelationshipsEquals(EmailImportDocument expected, EmailImportDocument actual) {
        assertThat(actual)
            .as("Verify EmailImportDocument relationships")
            .satisfies(a -> assertThat(a.getAppliedRule()).as("check appliedRule").isEqualTo(expected.getAppliedRule()));
    }
}
