package fr.smartprod.paperdms.emailimportdocument.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmailImportImportMappingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportImportMappingAllPropertiesEquals(
        EmailImportImportMapping expected,
        EmailImportImportMapping actual
    ) {
        assertEmailImportImportMappingAutoGeneratedPropertiesEquals(expected, actual);
        assertEmailImportImportMappingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportImportMappingAllUpdatablePropertiesEquals(
        EmailImportImportMapping expected,
        EmailImportImportMapping actual
    ) {
        assertEmailImportImportMappingUpdatableFieldsEquals(expected, actual);
        assertEmailImportImportMappingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportImportMappingAutoGeneratedPropertiesEquals(
        EmailImportImportMapping expected,
        EmailImportImportMapping actual
    ) {
        assertThat(actual)
            .as("Verify EmailImportImportMapping auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportImportMappingUpdatableFieldsEquals(
        EmailImportImportMapping expected,
        EmailImportImportMapping actual
    ) {
        assertThat(actual)
            .as("Verify EmailImportImportMapping relevant properties")
            .satisfies(a -> assertThat(a.getEmailField()).as("check emailField").isEqualTo(expected.getEmailField()))
            .satisfies(a -> assertThat(a.getDocumentField()).as("check documentField").isEqualTo(expected.getDocumentField()))
            .satisfies(a -> assertThat(a.getTransformation()).as("check transformation").isEqualTo(expected.getTransformation()))
            .satisfies(a ->
                assertThat(a.getTransformationConfig()).as("check transformationConfig").isEqualTo(expected.getTransformationConfig())
            )
            .satisfies(a -> assertThat(a.getIsRequired()).as("check isRequired").isEqualTo(expected.getIsRequired()))
            .satisfies(a -> assertThat(a.getDefaultValue()).as("check defaultValue").isEqualTo(expected.getDefaultValue()))
            .satisfies(a -> assertThat(a.getValidationRegex()).as("check validationRegex").isEqualTo(expected.getValidationRegex()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportImportMappingUpdatableRelationshipsEquals(
        EmailImportImportMapping expected,
        EmailImportImportMapping actual
    ) {
        assertThat(actual)
            .as("Verify EmailImportImportMapping relationships")
            .satisfies(a -> assertThat(a.getRule()).as("check rule").isEqualTo(expected.getRule()));
    }
}
