package fr.smartprod.paperdms.similarity.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentFingerprintAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentFingerprintAllPropertiesEquals(DocumentFingerprint expected, DocumentFingerprint actual) {
        assertDocumentFingerprintAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentFingerprintAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentFingerprintAllUpdatablePropertiesEquals(DocumentFingerprint expected, DocumentFingerprint actual) {
        assertDocumentFingerprintUpdatableFieldsEquals(expected, actual);
        assertDocumentFingerprintUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentFingerprintAutoGeneratedPropertiesEquals(DocumentFingerprint expected, DocumentFingerprint actual) {
        assertThat(actual)
            .as("Verify DocumentFingerprint auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentFingerprintUpdatableFieldsEquals(DocumentFingerprint expected, DocumentFingerprint actual) {
        assertThat(actual)
            .as("Verify DocumentFingerprint relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getFingerprintType()).as("check fingerprintType").isEqualTo(expected.getFingerprintType()))
            .satisfies(a -> assertThat(a.getFingerprint()).as("check fingerprint").isEqualTo(expected.getFingerprint()))
            .satisfies(a -> assertThat(a.getVectorEmbedding()).as("check vectorEmbedding").isEqualTo(expected.getVectorEmbedding()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()))
            .satisfies(a -> assertThat(a.getComputedDate()).as("check computedDate").isEqualTo(expected.getComputedDate()))
            .satisfies(a -> assertThat(a.getLastUpdated()).as("check lastUpdated").isEqualTo(expected.getLastUpdated()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentFingerprintUpdatableRelationshipsEquals(DocumentFingerprint expected, DocumentFingerprint actual) {
        // empty method
    }
}
