package fr.smartprod.paperdms.similarity.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentSimilarityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentSimilarityAllPropertiesEquals(DocumentSimilarity expected, DocumentSimilarity actual) {
        assertDocumentSimilarityAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentSimilarityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentSimilarityAllUpdatablePropertiesEquals(DocumentSimilarity expected, DocumentSimilarity actual) {
        assertDocumentSimilarityUpdatableFieldsEquals(expected, actual);
        assertDocumentSimilarityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentSimilarityAutoGeneratedPropertiesEquals(DocumentSimilarity expected, DocumentSimilarity actual) {
        assertThat(actual)
            .as("Verify DocumentSimilarity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentSimilarityUpdatableFieldsEquals(DocumentSimilarity expected, DocumentSimilarity actual) {
        assertThat(actual)
            .as("Verify DocumentSimilarity relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId1()).as("check documentId1").isEqualTo(expected.getDocumentId1()))
            .satisfies(a -> assertThat(a.getDocumentId2()).as("check documentId2").isEqualTo(expected.getDocumentId2()))
            .satisfies(a -> assertThat(a.getSimilarityScore()).as("check similarityScore").isEqualTo(expected.getSimilarityScore()))
            .satisfies(a -> assertThat(a.getAlgorithm()).as("check algorithm").isEqualTo(expected.getAlgorithm()))
            .satisfies(a -> assertThat(a.getFeatures()).as("check features").isEqualTo(expected.getFeatures()))
            .satisfies(a -> assertThat(a.getComputedDate()).as("check computedDate").isEqualTo(expected.getComputedDate()))
            .satisfies(a -> assertThat(a.getIsRelevant()).as("check isRelevant").isEqualTo(expected.getIsRelevant()))
            .satisfies(a -> assertThat(a.getReviewedBy()).as("check reviewedBy").isEqualTo(expected.getReviewedBy()))
            .satisfies(a -> assertThat(a.getReviewedDate()).as("check reviewedDate").isEqualTo(expected.getReviewedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentSimilarityUpdatableRelationshipsEquals(DocumentSimilarity expected, DocumentSimilarity actual) {
        assertThat(actual)
            .as("Verify DocumentSimilarity relationships")
            .satisfies(a -> assertThat(a.getJob()).as("check job").isEqualTo(expected.getJob()));
    }
}
