package fr.smartprod.paperdms.similarity.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SimilarityJobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityJobAllPropertiesEquals(SimilarityJob expected, SimilarityJob actual) {
        assertSimilarityJobAutoGeneratedPropertiesEquals(expected, actual);
        assertSimilarityJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityJobAllUpdatablePropertiesEquals(SimilarityJob expected, SimilarityJob actual) {
        assertSimilarityJobUpdatableFieldsEquals(expected, actual);
        assertSimilarityJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityJobAutoGeneratedPropertiesEquals(SimilarityJob expected, SimilarityJob actual) {
        assertThat(actual)
            .as("Verify SimilarityJob auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityJobUpdatableFieldsEquals(SimilarityJob expected, SimilarityJob actual) {
        assertThat(actual)
            .as("Verify SimilarityJob relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getAlgorithm()).as("check algorithm").isEqualTo(expected.getAlgorithm()))
            .satisfies(a -> assertThat(a.getScope()).as("check scope").isEqualTo(expected.getScope()))
            .satisfies(a ->
                assertThat(a.getMinSimilarityThreshold()).as("check minSimilarityThreshold").isEqualTo(expected.getMinSimilarityThreshold())
            )
            .satisfies(a -> assertThat(a.getMatchesFound()).as("check matchesFound").isEqualTo(expected.getMatchesFound()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityJobUpdatableRelationshipsEquals(SimilarityJob expected, SimilarityJob actual) {
        // empty method
    }
}
