package fr.smartprod.paperdms.emailimportdocument.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmailImportEmailAttachmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportEmailAttachmentAllPropertiesEquals(
        EmailImportEmailAttachment expected,
        EmailImportEmailAttachment actual
    ) {
        assertEmailImportEmailAttachmentAutoGeneratedPropertiesEquals(expected, actual);
        assertEmailImportEmailAttachmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportEmailAttachmentAllUpdatablePropertiesEquals(
        EmailImportEmailAttachment expected,
        EmailImportEmailAttachment actual
    ) {
        assertEmailImportEmailAttachmentUpdatableFieldsEquals(expected, actual);
        assertEmailImportEmailAttachmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportEmailAttachmentAutoGeneratedPropertiesEquals(
        EmailImportEmailAttachment expected,
        EmailImportEmailAttachment actual
    ) {
        assertThat(actual)
            .as("Verify EmailImportEmailAttachment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportEmailAttachmentUpdatableFieldsEquals(
        EmailImportEmailAttachment expected,
        EmailImportEmailAttachment actual
    ) {
        assertThat(actual)
            .as("Verify EmailImportEmailAttachment relevant properties")
            .satisfies(a -> assertThat(a.getFileName()).as("check fileName").isEqualTo(expected.getFileName()))
            .satisfies(a -> assertThat(a.getFileSize()).as("check fileSize").isEqualTo(expected.getFileSize()))
            .satisfies(a -> assertThat(a.getMimeType()).as("check mimeType").isEqualTo(expected.getMimeType()))
            .satisfies(a -> assertThat(a.getSha256()).as("check sha256").isEqualTo(expected.getSha256()))
            .satisfies(a -> assertThat(a.gets3Key()).as("check s3Key").isEqualTo(expected.gets3Key()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportEmailAttachmentUpdatableRelationshipsEquals(
        EmailImportEmailAttachment expected,
        EmailImportEmailAttachment actual
    ) {
        assertThat(actual)
            .as("Verify EmailImportEmailAttachment relationships")
            .satisfies(a ->
                assertThat(a.getEmailImportDocument()).as("check emailImportDocument").isEqualTo(expected.getEmailImportDocument())
            );
    }
}
