package fr.smartprod.paperdms.emailimportdocument.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmailImportImportRuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportImportRuleAllPropertiesEquals(EmailImportImportRule expected, EmailImportImportRule actual) {
        assertEmailImportImportRuleAutoGeneratedPropertiesEquals(expected, actual);
        assertEmailImportImportRuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportImportRuleAllUpdatablePropertiesEquals(
        EmailImportImportRule expected,
        EmailImportImportRule actual
    ) {
        assertEmailImportImportRuleUpdatableFieldsEquals(expected, actual);
        assertEmailImportImportRuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportImportRuleAutoGeneratedPropertiesEquals(
        EmailImportImportRule expected,
        EmailImportImportRule actual
    ) {
        assertThat(actual)
            .as("Verify EmailImportImportRule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportImportRuleUpdatableFieldsEquals(EmailImportImportRule expected, EmailImportImportRule actual) {
        assertThat(actual)
            .as("Verify EmailImportImportRule relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getConditions()).as("check conditions").isEqualTo(expected.getConditions()))
            .satisfies(a -> assertThat(a.getActions()).as("check actions").isEqualTo(expected.getActions()))
            .satisfies(a -> assertThat(a.getNotifyUsers()).as("check notifyUsers").isEqualTo(expected.getNotifyUsers()))
            .satisfies(a -> assertThat(a.getMatchCount()).as("check matchCount").isEqualTo(expected.getMatchCount()))
            .satisfies(a -> assertThat(a.getLastMatchDate()).as("check lastMatchDate").isEqualTo(expected.getLastMatchDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailImportImportRuleUpdatableRelationshipsEquals(
        EmailImportImportRule expected,
        EmailImportImportRule actual
    ) {
        // empty method
    }
}
