package fr.smartprod.paperdms.archive.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ArchiveDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArchiveDocumentAllPropertiesEquals(ArchiveDocument expected, ArchiveDocument actual) {
        assertArchiveDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertArchiveDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArchiveDocumentAllUpdatablePropertiesEquals(ArchiveDocument expected, ArchiveDocument actual) {
        assertArchiveDocumentUpdatableFieldsEquals(expected, actual);
        assertArchiveDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArchiveDocumentAutoGeneratedPropertiesEquals(ArchiveDocument expected, ArchiveDocument actual) {
        assertThat(actual)
            .as("Verify ArchiveDocument auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArchiveDocumentUpdatableFieldsEquals(ArchiveDocument expected, ArchiveDocument actual) {
        assertThat(actual)
            .as("Verify ArchiveDocument relevant properties")
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()))
            .satisfies(a -> assertThat(a.getOriginalPath()).as("check originalPath").isEqualTo(expected.getOriginalPath()))
            .satisfies(a -> assertThat(a.getArchivePath()).as("check archivePath").isEqualTo(expected.getArchivePath()))
            .satisfies(a -> assertThat(a.getFileSize()).as("check fileSize").isEqualTo(expected.getFileSize()))
            .satisfies(a -> assertThat(a.getAddedDate()).as("check addedDate").isEqualTo(expected.getAddedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArchiveDocumentUpdatableRelationshipsEquals(ArchiveDocument expected, ArchiveDocument actual) {
        assertThat(actual)
            .as("Verify ArchiveDocument relationships")
            .satisfies(a -> assertThat(a.getArchiveJob()).as("check archiveJob").isEqualTo(expected.getArchiveJob()));
    }
}
