package fr.smartprod.paperdms.archive.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ArchiveJobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArchiveJobAllPropertiesEquals(ArchiveJob expected, ArchiveJob actual) {
        assertArchiveJobAutoGeneratedPropertiesEquals(expected, actual);
        assertArchiveJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArchiveJobAllUpdatablePropertiesEquals(ArchiveJob expected, ArchiveJob actual) {
        assertArchiveJobUpdatableFieldsEquals(expected, actual);
        assertArchiveJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArchiveJobAutoGeneratedPropertiesEquals(ArchiveJob expected, ArchiveJob actual) {
        assertThat(actual)
            .as("Verify ArchiveJob auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArchiveJobUpdatableFieldsEquals(ArchiveJob expected, ArchiveJob actual) {
        assertThat(actual)
            .as("Verify ArchiveJob relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getDocumentQuery()).as("check documentQuery").isEqualTo(expected.getDocumentQuery()))
            .satisfies(a -> assertThat(a.getArchiveFormat()).as("check archiveFormat").isEqualTo(expected.getArchiveFormat()))
            .satisfies(a -> assertThat(a.getCompressionLevel()).as("check compressionLevel").isEqualTo(expected.getCompressionLevel()))
            .satisfies(a -> assertThat(a.getEncryptionEnabled()).as("check encryptionEnabled").isEqualTo(expected.getEncryptionEnabled()))
            .satisfies(a ->
                assertThat(a.getEncryptionAlgorithm()).as("check encryptionAlgorithm").isEqualTo(expected.getEncryptionAlgorithm())
            )
            .satisfies(a -> assertThat(a.getPassword()).as("check password").isEqualTo(expected.getPassword()))
            .satisfies(a -> assertThat(a.gets3ArchiveKey()).as("check s3ArchiveKey").isEqualTo(expected.gets3ArchiveKey()))
            .satisfies(a -> assertThat(a.getArchiveSha256()).as("check archiveSha256").isEqualTo(expected.getArchiveSha256()))
            .satisfies(a -> assertThat(a.getArchiveSize()).as("check archiveSize").isEqualTo(expected.getArchiveSize()))
            .satisfies(a -> assertThat(a.getDocumentCount()).as("check documentCount").isEqualTo(expected.getDocumentCount()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArchiveJobUpdatableRelationshipsEquals(ArchiveJob expected, ArchiveJob actual) {
        // empty method
    }
}
