export enum AuditAction {
  CREATED = 'CREATED',

  VIEWED = 'VIEWED',

  DOWNLOADED = 'DOWNLOADED',

  MODIFIED = 'MODIFIED',

  DELETED = 'DELETED',

  SHARED = 'SHARED',

  PRINTED = 'PRINTED',

  EXPORTED = 'EXPORTED',

  PERMISSIONS_CHANGED = 'PERMISSIONS_CHANGED',

  WORKFLOW_STARTED = 'WORKFLOW_STARTED',

  WORKFLOW_COMPLETED = 'WORKFLOW_COMPLETED',

  COMMENTED = 'COMMENTED',

  RELATION_ADDED = 'RELATION_ADDED',

  RELATION_REMOVED = 'RELATION_REMOVED',

  ARCHIVED = 'ARCHIVED',

  RESTORED = 'RESTORED',

  SERVICE_STATUS_CHANGED = 'SERVICE_STATUS_CHANGED',
}
