export enum MaintenanceType {
  CLEANUP_DELETED = 'CLEANUP_DELETED',

  REBUILD_INDEX = 'REBUILD_INDEX',

  OPTIMIZE_STORAGE = 'OPTIMIZE_STORAGE',

  VERIFY_CHECKSUMS = 'VERIFY_CHECKSUMS',

  EXPIRE_TEMP_FILES = 'EXPIRE_TEMP_FILES',

  PRUNE_AUDIT_LOGS = 'PRUNE_AUDIT_LOGS',

  UPDATE_STATISTICS = 'UPDATE_STATISTICS',

  VACUUM_DATABASE = 'VACUUM_DATABASE',

  ROTATE_LOGS = 'ROTATE_LOGS',

  BACKUP_DATABASE = 'BACKUP_DATABASE',
}
