export enum MetricType {
  UPLOAD_SPEED = 'UPLOAD_SPEED',

  OCR_DURATION = 'OCR_DURATION',

  SEARCH_LATENCY = 'SEARCH_LATENCY',

  API_RESPONSE_TIME = 'API_RESPONSE_TIME',

  STORAGE_IOPS = 'STORAGE_IOPS',

  CACHE_HIT_RATE = 'CACHE_HIT_RATE',

  QUEUE_LENGTH = 'QUEUE_LENGTH',

  ERROR_RATE = 'ERROR_RATE',

  THROUGHPUT = 'THROUGHPUT',

  CONCURRENT_USERS = 'CONCURRENT_USERS',
}
