export enum ServiceStatus {
  NOT_APPLICABLE = 'NOT_APPLICABLE',

  PENDING = 'PENDING',

  QUEUED = 'QUEUED',

  IN_PROGRESS = 'IN_PROGRESS',

  COMPLETED = 'COMPLETED',

  FAILED = 'FAILED',

  CANCELLED = 'CANCELLED',

  SKIPPED = 'SKIPPED',

  RETRYING = 'RETRYING',

  PARTIALLY_COMPLETED = 'PARTIALLY_COMPLETED',
}
