export enum ServiceType {
  OCR_SERVICE = 'OCR_SERVICE',

  AI_SERVICE = 'AI_SERVICE',

  WORKFLOW_SERVICE = 'WORKFLOW_SERVICE',

  SEARCH_SERVICE = 'SEARCH_SERVICE',

  TRANSFORM_SERVICE = 'TRANSFORM_SERVICE',

  ARCHIVE_SERVICE = 'ARCHIVE_SERVICE',

  EXPORT_SERVICE = 'EXPORT_SERVICE',

  SIMILARITY_SERVICE = 'SIMILARITY_SERVICE',

  BUSINESS_SERVICE = 'BUSINESS_SERVICE',

  SCAN_SERVICE = 'SCAN_SERVICE',

  EMAIL_IMPORT_SERVICE = 'EMAIL_IMPORT_SERVICE',

  REPORTING_SERVICE = 'REPORTING_SERVICE',

  MONITORING_SERVICE = 'MONITORING_SERVICE',
}
