package fr.smartprod.paperdms.scan.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ScanJobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScanJobAllPropertiesEquals(ScanJob expected, ScanJob actual) {
        assertScanJobAutoGeneratedPropertiesEquals(expected, actual);
        assertScanJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScanJobAllUpdatablePropertiesEquals(ScanJob expected, ScanJob actual) {
        assertScanJobUpdatableFieldsEquals(expected, actual);
        assertScanJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScanJobAutoGeneratedPropertiesEquals(ScanJob expected, ScanJob actual) {
        assertThat(actual)
            .as("Verify ScanJob auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScanJobUpdatableFieldsEquals(ScanJob expected, ScanJob actual) {
        assertThat(actual)
            .as("Verify ScanJob relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getScannerConfigId()).as("check scannerConfigId").isEqualTo(expected.getScannerConfigId()))
            .satisfies(a -> assertThat(a.getBatchId()).as("check batchId").isEqualTo(expected.getBatchId()))
            .satisfies(a -> assertThat(a.getDocumentTypeId()).as("check documentTypeId").isEqualTo(expected.getDocumentTypeId()))
            .satisfies(a -> assertThat(a.getFolderId()).as("check folderId").isEqualTo(expected.getFolderId()))
            .satisfies(a -> assertThat(a.getPageCount()).as("check pageCount").isEqualTo(expected.getPageCount()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getColorMode()).as("check colorMode").isEqualTo(expected.getColorMode()))
            .satisfies(a -> assertThat(a.getResolution()).as("check resolution").isEqualTo(expected.getResolution()))
            .satisfies(a -> assertThat(a.getFileFormat()).as("check fileFormat").isEqualTo(expected.getFileFormat()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScanJobUpdatableRelationshipsEquals(ScanJob expected, ScanJob actual) {
        assertThat(actual)
            .as("Verify ScanJob relationships")
            .satisfies(a -> assertThat(a.getScannerConfig()).as("check scannerConfig").isEqualTo(expected.getScannerConfig()))
            .satisfies(a -> assertThat(a.getBatch()).as("check batch").isEqualTo(expected.getBatch()));
    }
}
