package fr.smartprod.paperdms.scan.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ScanBatchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScanBatchAllPropertiesEquals(ScanBatch expected, ScanBatch actual) {
        assertScanBatchAutoGeneratedPropertiesEquals(expected, actual);
        assertScanBatchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScanBatchAllUpdatablePropertiesEquals(ScanBatch expected, ScanBatch actual) {
        assertScanBatchUpdatableFieldsEquals(expected, actual);
        assertScanBatchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScanBatchAutoGeneratedPropertiesEquals(ScanBatch expected, ScanBatch actual) {
        assertThat(actual)
            .as("Verify ScanBatch auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScanBatchUpdatableFieldsEquals(ScanBatch expected, ScanBatch actual) {
        assertThat(actual)
            .as("Verify ScanBatch relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getTotalJobs()).as("check totalJobs").isEqualTo(expected.getTotalJobs()))
            .satisfies(a -> assertThat(a.getCompletedJobs()).as("check completedJobs").isEqualTo(expected.getCompletedJobs()))
            .satisfies(a -> assertThat(a.getTotalPages()).as("check totalPages").isEqualTo(expected.getTotalPages()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScanBatchUpdatableRelationshipsEquals(ScanBatch expected, ScanBatch actual) {
        // empty method
    }
}
