package fr.smartprod.paperdms.emailimport.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EmailAttachmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailAttachmentAllPropertiesEquals(EmailAttachment expected, EmailAttachment actual) {
        assertEmailAttachmentAutoGeneratedPropertiesEquals(expected, actual);
        assertEmailAttachmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailAttachmentAllUpdatablePropertiesEquals(EmailAttachment expected, EmailAttachment actual) {
        assertEmailAttachmentUpdatableFieldsEquals(expected, actual);
        assertEmailAttachmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailAttachmentAutoGeneratedPropertiesEquals(EmailAttachment expected, EmailAttachment actual) {
        assertThat(actual)
            .as("Verify EmailAttachment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailAttachmentUpdatableFieldsEquals(EmailAttachment expected, EmailAttachment actual) {
        assertThat(actual)
            .as("Verify EmailAttachment relevant properties")
            .satisfies(a -> assertThat(a.getEmailImportId()).as("check emailImportId").isEqualTo(expected.getEmailImportId()))
            .satisfies(a -> assertThat(a.getFileName()).as("check fileName").isEqualTo(expected.getFileName()))
            .satisfies(a -> assertThat(a.getFileSize()).as("check fileSize").isEqualTo(expected.getFileSize()))
            .satisfies(a -> assertThat(a.getMimeType()).as("check mimeType").isEqualTo(expected.getMimeType()))
            .satisfies(a -> assertThat(a.getSha256()).as("check sha256").isEqualTo(expected.getSha256()))
            .satisfies(a -> assertThat(a.gets3Key()).as("check s3Key").isEqualTo(expected.gets3Key()))
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEmailAttachmentUpdatableRelationshipsEquals(EmailAttachment expected, EmailAttachment actual) {
        assertThat(actual)
            .as("Verify EmailAttachment relationships")
            .satisfies(a -> assertThat(a.getEmailImport()).as("check emailImport").isEqualTo(expected.getEmailImport()));
    }
}
