package fr.smartprod.paperdms.emailimport.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImportRuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportRuleAllPropertiesEquals(ImportRule expected, ImportRule actual) {
        assertImportRuleAutoGeneratedPropertiesEquals(expected, actual);
        assertImportRuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportRuleAllUpdatablePropertiesEquals(ImportRule expected, ImportRule actual) {
        assertImportRuleUpdatableFieldsEquals(expected, actual);
        assertImportRuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportRuleAutoGeneratedPropertiesEquals(ImportRule expected, ImportRule actual) {
        assertThat(actual)
            .as("Verify ImportRule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportRuleUpdatableFieldsEquals(ImportRule expected, ImportRule actual) {
        assertThat(actual)
            .as("Verify ImportRule relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getConditions()).as("check conditions").isEqualTo(expected.getConditions()))
            .satisfies(a -> assertThat(a.getActions()).as("check actions").isEqualTo(expected.getActions()))
            .satisfies(a -> assertThat(a.getFolderId()).as("check folderId").isEqualTo(expected.getFolderId()))
            .satisfies(a -> assertThat(a.getDocumentTypeId()).as("check documentTypeId").isEqualTo(expected.getDocumentTypeId()))
            .satisfies(a -> assertThat(a.getApplyTags()).as("check applyTags").isEqualTo(expected.getApplyTags()))
            .satisfies(a -> assertThat(a.getNotifyUsers()).as("check notifyUsers").isEqualTo(expected.getNotifyUsers()))
            .satisfies(a -> assertThat(a.getMatchCount()).as("check matchCount").isEqualTo(expected.getMatchCount()))
            .satisfies(a -> assertThat(a.getLastMatchDate()).as("check lastMatchDate").isEqualTo(expected.getLastMatchDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportRuleUpdatableRelationshipsEquals(ImportRule expected, ImportRule actual) {
        // empty method
    }
}
