package fr.smartprod.paperdms.emailimport.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImportMappingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportMappingAllPropertiesEquals(ImportMapping expected, ImportMapping actual) {
        assertImportMappingAutoGeneratedPropertiesEquals(expected, actual);
        assertImportMappingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportMappingAllUpdatablePropertiesEquals(ImportMapping expected, ImportMapping actual) {
        assertImportMappingUpdatableFieldsEquals(expected, actual);
        assertImportMappingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportMappingAutoGeneratedPropertiesEquals(ImportMapping expected, ImportMapping actual) {
        assertThat(actual)
            .as("Verify ImportMapping auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportMappingUpdatableFieldsEquals(ImportMapping expected, ImportMapping actual) {
        assertThat(actual)
            .as("Verify ImportMapping relevant properties")
            .satisfies(a -> assertThat(a.getRuleId()).as("check ruleId").isEqualTo(expected.getRuleId()))
            .satisfies(a -> assertThat(a.getEmailField()).as("check emailField").isEqualTo(expected.getEmailField()))
            .satisfies(a -> assertThat(a.getDocumentField()).as("check documentField").isEqualTo(expected.getDocumentField()))
            .satisfies(a -> assertThat(a.getTransformation()).as("check transformation").isEqualTo(expected.getTransformation()))
            .satisfies(a ->
                assertThat(a.getTransformationConfig()).as("check transformationConfig").isEqualTo(expected.getTransformationConfig())
            )
            .satisfies(a -> assertThat(a.getIsRequired()).as("check isRequired").isEqualTo(expected.getIsRequired()))
            .satisfies(a -> assertThat(a.getDefaultValue()).as("check defaultValue").isEqualTo(expected.getDefaultValue()))
            .satisfies(a -> assertThat(a.getValidationRegex()).as("check validationRegex").isEqualTo(expected.getValidationRegex()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImportMappingUpdatableRelationshipsEquals(ImportMapping expected, ImportMapping actual) {
        assertThat(actual)
            .as("Verify ImportMapping relationships")
            .satisfies(a -> assertThat(a.getRule()).as("check rule").isEqualTo(expected.getRule()));
    }
}
