package fr.smartprod.paperdms.ai.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AICorrespondentPredictionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAICorrespondentPredictionAllPropertiesEquals(
        AICorrespondentPrediction expected,
        AICorrespondentPrediction actual
    ) {
        assertAICorrespondentPredictionAutoGeneratedPropertiesEquals(expected, actual);
        assertAICorrespondentPredictionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAICorrespondentPredictionAllUpdatablePropertiesEquals(
        AICorrespondentPrediction expected,
        AICorrespondentPrediction actual
    ) {
        assertAICorrespondentPredictionUpdatableFieldsEquals(expected, actual);
        assertAICorrespondentPredictionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAICorrespondentPredictionAutoGeneratedPropertiesEquals(
        AICorrespondentPrediction expected,
        AICorrespondentPrediction actual
    ) {
        assertThat(actual)
            .as("Verify AICorrespondentPrediction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAICorrespondentPredictionUpdatableFieldsEquals(
        AICorrespondentPrediction expected,
        AICorrespondentPrediction actual
    ) {
        assertThat(actual)
            .as("Verify AICorrespondentPrediction relevant properties")
            .satisfies(a -> assertThat(a.getCorrespondentName()).as("check correspondentName").isEqualTo(expected.getCorrespondentName()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getCompany()).as("check company").isEqualTo(expected.getCompany()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getModelVersion()).as("check modelVersion").isEqualTo(expected.getModelVersion()))
            .satisfies(a -> assertThat(a.getPredictionS3Key()).as("check predictionS3Key").isEqualTo(expected.getPredictionS3Key()))
            .satisfies(a -> assertThat(a.getIsAccepted()).as("check isAccepted").isEqualTo(expected.getIsAccepted()))
            .satisfies(a -> assertThat(a.getAcceptedBy()).as("check acceptedBy").isEqualTo(expected.getAcceptedBy()))
            .satisfies(a -> assertThat(a.getAcceptedDate()).as("check acceptedDate").isEqualTo(expected.getAcceptedDate()))
            .satisfies(a -> assertThat(a.getPredictionDate()).as("check predictionDate").isEqualTo(expected.getPredictionDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAICorrespondentPredictionUpdatableRelationshipsEquals(
        AICorrespondentPrediction expected,
        AICorrespondentPrediction actual
    ) {
        assertThat(actual)
            .as("Verify AICorrespondentPrediction relationships")
            .satisfies(a -> assertThat(a.getJob()).as("check job").isEqualTo(expected.getJob()));
    }
}
