---
# Service Discovery - Eureka Server
# metadata/infrastructure/eureka.yaml

category: infrastructure
type: discovery
name: "discovery-server"
enabled: true

service:
  artifactId: "discovery-server"
  port: 8761
  packageName: "com.example.discovery"
  
  dependencies:
    - spring-boot-starter-web
    - spring-cloud-starter-netflix-eureka-server
    - spring-boot-starter-actuator
    - micrometer-registry-prometheus
  
  resources:
    memory: "512m"
    cpus: "0.5"
  
  healthCheck:
    endpoint: "/actuator/health"
    interval: "30s"
    timeout: "10s"
    retries: 5
  
  environment:
    - "SPRING_PROFILES_ACTIVE=docker"
    - "EUREKA_CLIENT_REGISTER_WITH_EUREKA=false"
    - "EUREKA_CLIENT_FETCH_REGISTRY=false"

frontend:
  displayName: "Service Discovery"
  icon: "pi pi-sitemap"
  menuPosition: 100

docker:
  image: "discovery-server"
  containerName: "eureka-server"
