package fr.smartprod.paperdms.pdftoimage.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImageConversionBatchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionBatchAllPropertiesEquals(ImageConversionBatch expected, ImageConversionBatch actual) {
        assertImageConversionBatchAutoGeneratedPropertiesEquals(expected, actual);
        assertImageConversionBatchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionBatchAllUpdatablePropertiesEquals(ImageConversionBatch expected, ImageConversionBatch actual) {
        assertImageConversionBatchUpdatableFieldsEquals(expected, actual);
        assertImageConversionBatchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionBatchAutoGeneratedPropertiesEquals(ImageConversionBatch expected, ImageConversionBatch actual) {
        assertThat(actual)
            .as("Verify ImageConversionBatch auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionBatchUpdatableFieldsEquals(ImageConversionBatch expected, ImageConversionBatch actual) {
        assertThat(actual)
            .as("Verify ImageConversionBatch relevant properties")
            .satisfies(a -> assertThat(a.getBatchName()).as("check batchName").isEqualTo(expected.getBatchName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getTotalConversions()).as("check totalConversions").isEqualTo(expected.getTotalConversions()))
            .satisfies(a ->
                assertThat(a.getCompletedConversions()).as("check completedConversions").isEqualTo(expected.getCompletedConversions())
            )
            .satisfies(a -> assertThat(a.getFailedConversions()).as("check failedConversions").isEqualTo(expected.getFailedConversions()))
            .satisfies(a -> assertThat(a.getStartedAt()).as("check startedAt").isEqualTo(expected.getStartedAt()))
            .satisfies(a -> assertThat(a.getCompletedAt()).as("check completedAt").isEqualTo(expected.getCompletedAt()))
            .satisfies(a ->
                assertThat(a.getTotalProcessingDuration())
                    .as("check totalProcessingDuration")
                    .isEqualTo(expected.getTotalProcessingDuration())
            )
            .satisfies(a -> assertThat(a.getCreatedByUserId()).as("check createdByUserId").isEqualTo(expected.getCreatedByUserId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionBatchUpdatableRelationshipsEquals(ImageConversionBatch expected, ImageConversionBatch actual) {
        // empty method
    }
}
