package fr.smartprod.paperdms.pdftoimage.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImageConversionStatisticsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionStatisticsAllPropertiesEquals(
        ImageConversionStatistics expected,
        ImageConversionStatistics actual
    ) {
        assertImageConversionStatisticsAutoGeneratedPropertiesEquals(expected, actual);
        assertImageConversionStatisticsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionStatisticsAllUpdatablePropertiesEquals(
        ImageConversionStatistics expected,
        ImageConversionStatistics actual
    ) {
        assertImageConversionStatisticsUpdatableFieldsEquals(expected, actual);
        assertImageConversionStatisticsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionStatisticsAutoGeneratedPropertiesEquals(
        ImageConversionStatistics expected,
        ImageConversionStatistics actual
    ) {
        assertThat(actual)
            .as("Verify ImageConversionStatistics auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionStatisticsUpdatableFieldsEquals(
        ImageConversionStatistics expected,
        ImageConversionStatistics actual
    ) {
        assertThat(actual)
            .as("Verify ImageConversionStatistics relevant properties")
            .satisfies(a -> assertThat(a.getStatisticsDate()).as("check statisticsDate").isEqualTo(expected.getStatisticsDate()))
            .satisfies(a -> assertThat(a.getTotalConversions()).as("check totalConversions").isEqualTo(expected.getTotalConversions()))
            .satisfies(a ->
                assertThat(a.getSuccessfulConversions()).as("check successfulConversions").isEqualTo(expected.getSuccessfulConversions())
            )
            .satisfies(a -> assertThat(a.getFailedConversions()).as("check failedConversions").isEqualTo(expected.getFailedConversions()))
            .satisfies(a ->
                assertThat(a.getTotalPagesConverted()).as("check totalPagesConverted").isEqualTo(expected.getTotalPagesConverted())
            )
            .satisfies(a ->
                assertThat(a.getTotalImagesGenerated()).as("check totalImagesGenerated").isEqualTo(expected.getTotalImagesGenerated())
            )
            .satisfies(a -> assertThat(a.getTotalImagesSize()).as("check totalImagesSize").isEqualTo(expected.getTotalImagesSize()))
            .satisfies(a ->
                assertThat(a.getAverageProcessingDuration())
                    .as("check averageProcessingDuration")
                    .isEqualTo(expected.getAverageProcessingDuration())
            )
            .satisfies(a ->
                assertThat(a.getMaxProcessingDuration()).as("check maxProcessingDuration").isEqualTo(expected.getMaxProcessingDuration())
            )
            .satisfies(a ->
                assertThat(a.getMinProcessingDuration()).as("check minProcessingDuration").isEqualTo(expected.getMinProcessingDuration())
            )
            .satisfies(a -> assertThat(a.getCalculatedAt()).as("check calculatedAt").isEqualTo(expected.getCalculatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImageConversionStatisticsUpdatableRelationshipsEquals(
        ImageConversionStatistics expected,
        ImageConversionStatistics actual
    ) {
        // empty method
    }
}
