package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentVersionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentVersionAllPropertiesEquals(DocumentVersion expected, DocumentVersion actual) {
        assertDocumentVersionAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentVersionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentVersionAllUpdatablePropertiesEquals(DocumentVersion expected, DocumentVersion actual) {
        assertDocumentVersionUpdatableFieldsEquals(expected, actual);
        assertDocumentVersionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentVersionAutoGeneratedPropertiesEquals(DocumentVersion expected, DocumentVersion actual) {
        assertThat(actual)
            .as("Verify DocumentVersion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentVersionUpdatableFieldsEquals(DocumentVersion expected, DocumentVersion actual) {
        assertThat(actual)
            .as("Verify DocumentVersion relevant properties")
            .satisfies(a -> assertThat(a.getVersionNumber()).as("check versionNumber").isEqualTo(expected.getVersionNumber()))
            .satisfies(a -> assertThat(a.getSha256()).as("check sha256").isEqualTo(expected.getSha256()))
            .satisfies(a -> assertThat(a.gets3Key()).as("check s3Key").isEqualTo(expected.gets3Key()))
            .satisfies(a -> assertThat(a.getFileSize()).as("check fileSize").isEqualTo(expected.getFileSize()))
            .satisfies(a -> assertThat(a.getUploadDate()).as("check uploadDate").isEqualTo(expected.getUploadDate()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentVersionUpdatableRelationshipsEquals(DocumentVersion expected, DocumentVersion actual) {
        assertThat(actual)
            .as("Verify DocumentVersion relationships")
            .satisfies(a -> assertThat(a.getDocument()).as("check document").isEqualTo(expected.getDocument()));
    }
}
