package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentAuditAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentAuditAllPropertiesEquals(DocumentAudit expected, DocumentAudit actual) {
        assertDocumentAuditAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentAuditAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentAuditAllUpdatablePropertiesEquals(DocumentAudit expected, DocumentAudit actual) {
        assertDocumentAuditUpdatableFieldsEquals(expected, actual);
        assertDocumentAuditUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentAuditAutoGeneratedPropertiesEquals(DocumentAudit expected, DocumentAudit actual) {
        assertThat(actual)
            .as("Verify DocumentAudit auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentAuditUpdatableFieldsEquals(DocumentAudit expected, DocumentAudit actual) {
        assertThat(actual)
            .as("Verify DocumentAudit relevant properties")
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()))
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getUserIp()).as("check userIp").isEqualTo(expected.getUserIp()))
            .satisfies(a -> assertThat(a.getActionDate()).as("check actionDate").isEqualTo(expected.getActionDate()))
            .satisfies(a -> assertThat(a.getAdditionalInfo()).as("check additionalInfo").isEqualTo(expected.getAdditionalInfo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentAuditUpdatableRelationshipsEquals(DocumentAudit expected, DocumentAudit actual) {
        assertThat(actual)
            .as("Verify DocumentAudit relationships")
            .satisfies(a -> assertThat(a.getDocument()).as("check document").isEqualTo(expected.getDocument()));
    }
}
