package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MetaTagAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaTagAllPropertiesEquals(MetaTag expected, MetaTag actual) {
        assertMetaTagAutoGeneratedPropertiesEquals(expected, actual);
        assertMetaTagAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaTagAllUpdatablePropertiesEquals(MetaTag expected, MetaTag actual) {
        assertMetaTagUpdatableFieldsEquals(expected, actual);
        assertMetaTagUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaTagAutoGeneratedPropertiesEquals(MetaTag expected, MetaTag actual) {
        assertThat(actual)
            .as("Verify MetaTag auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaTagUpdatableFieldsEquals(MetaTag expected, MetaTag actual) {
        assertThat(actual)
            .as("Verify MetaTag relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getColor()).as("check color").isEqualTo(expected.getColor()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getUsageCount()).as("check usageCount").isEqualTo(expected.getUsageCount()))
            .satisfies(a -> assertThat(a.getIsSystem()).as("check isSystem").isEqualTo(expected.getIsSystem()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaTagUpdatableRelationshipsEquals(MetaTag expected, MetaTag actual) {
        assertThat(actual)
            .as("Verify MetaTag relationships")
            .satisfies(a ->
                assertThat(a.getMetaMetaTagCategory()).as("check metaMetaTagCategory").isEqualTo(expected.getMetaMetaTagCategory())
            );
    }
}
