package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MetaMetaTagCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaMetaTagCategoryAllPropertiesEquals(MetaMetaTagCategory expected, MetaMetaTagCategory actual) {
        assertMetaMetaTagCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertMetaMetaTagCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaMetaTagCategoryAllUpdatablePropertiesEquals(MetaMetaTagCategory expected, MetaMetaTagCategory actual) {
        assertMetaMetaTagCategoryUpdatableFieldsEquals(expected, actual);
        assertMetaMetaTagCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaMetaTagCategoryAutoGeneratedPropertiesEquals(MetaMetaTagCategory expected, MetaMetaTagCategory actual) {
        assertThat(actual)
            .as("Verify MetaMetaTagCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaMetaTagCategoryUpdatableFieldsEquals(MetaMetaTagCategory expected, MetaMetaTagCategory actual) {
        assertThat(actual)
            .as("Verify MetaMetaTagCategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getColor()).as("check color").isEqualTo(expected.getColor()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getIsSystem()).as("check isSystem").isEqualTo(expected.getIsSystem()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaMetaTagCategoryUpdatableRelationshipsEquals(MetaMetaTagCategory expected, MetaMetaTagCategory actual) {
        assertThat(actual)
            .as("Verify MetaMetaTagCategory relationships")
            .satisfies(a -> assertThat(a.getParent()).as("check parent").isEqualTo(expected.getParent()));
    }
}
