package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MetaSavedSearchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaSavedSearchAllPropertiesEquals(MetaSavedSearch expected, MetaSavedSearch actual) {
        assertMetaSavedSearchAutoGeneratedPropertiesEquals(expected, actual);
        assertMetaSavedSearchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaSavedSearchAllUpdatablePropertiesEquals(MetaSavedSearch expected, MetaSavedSearch actual) {
        assertMetaSavedSearchUpdatableFieldsEquals(expected, actual);
        assertMetaSavedSearchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaSavedSearchAutoGeneratedPropertiesEquals(MetaSavedSearch expected, MetaSavedSearch actual) {
        assertThat(actual)
            .as("Verify MetaSavedSearch auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaSavedSearchUpdatableFieldsEquals(MetaSavedSearch expected, MetaSavedSearch actual) {
        assertThat(actual)
            .as("Verify MetaSavedSearch relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getQuery()).as("check query").isEqualTo(expected.getQuery()))
            .satisfies(a -> assertThat(a.getIsPublic()).as("check isPublic").isEqualTo(expected.getIsPublic()))
            .satisfies(a -> assertThat(a.getIsAlert()).as("check isAlert").isEqualTo(expected.getIsAlert()))
            .satisfies(a -> assertThat(a.getAlertFrequency()).as("check alertFrequency").isEqualTo(expected.getAlertFrequency()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaSavedSearchUpdatableRelationshipsEquals(MetaSavedSearch expected, MetaSavedSearch actual) {
        // empty method
    }
}
