package fr.smartprod.paperdms.business.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BankStatementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankStatementAllPropertiesEquals(BankStatement expected, BankStatement actual) {
        assertBankStatementAutoGeneratedPropertiesEquals(expected, actual);
        assertBankStatementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankStatementAllUpdatablePropertiesEquals(BankStatement expected, BankStatement actual) {
        assertBankStatementUpdatableFieldsEquals(expected, actual);
        assertBankStatementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankStatementAutoGeneratedPropertiesEquals(BankStatement expected, BankStatement actual) {
        assertThat(actual)
            .as("Verify BankStatement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankStatementUpdatableFieldsEquals(BankStatement expected, BankStatement actual) {
        assertThat(actual)
            .as("Verify BankStatement relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getAccountNumber()).as("check accountNumber").isEqualTo(expected.getAccountNumber()))
            .satisfies(a -> assertThat(a.getBankName()).as("check bankName").isEqualTo(expected.getBankName()))
            .satisfies(a -> assertThat(a.getStatementDate()).as("check statementDate").isEqualTo(expected.getStatementDate()))
            .satisfies(a ->
                assertThat(a.getStatementPeriodStart()).as("check statementPeriodStart").isEqualTo(expected.getStatementPeriodStart())
            )
            .satisfies(a ->
                assertThat(a.getStatementPeriodEnd()).as("check statementPeriodEnd").isEqualTo(expected.getStatementPeriodEnd())
            )
            .satisfies(a -> assertThat(a.getOpeningBalance()).as("check openingBalance").isEqualTo(expected.getOpeningBalance()))
            .satisfies(a -> assertThat(a.getClosingBalance()).as("check closingBalance").isEqualTo(expected.getClosingBalance()))
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getIsReconciled()).as("check isReconciled").isEqualTo(expected.getIsReconciled()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankStatementUpdatableRelationshipsEquals(BankStatement expected, BankStatement actual) {
        // empty method
    }
}
