package fr.smartprod.paperdms.business.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContractClauseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractClauseAllPropertiesEquals(ContractClause expected, ContractClause actual) {
        assertContractClauseAutoGeneratedPropertiesEquals(expected, actual);
        assertContractClauseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractClauseAllUpdatablePropertiesEquals(ContractClause expected, ContractClause actual) {
        assertContractClauseUpdatableFieldsEquals(expected, actual);
        assertContractClauseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractClauseAutoGeneratedPropertiesEquals(ContractClause expected, ContractClause actual) {
        assertThat(actual)
            .as("Verify ContractClause auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractClauseUpdatableFieldsEquals(ContractClause expected, ContractClause actual) {
        assertThat(actual)
            .as("Verify ContractClause relevant properties")
            .satisfies(a -> assertThat(a.getContractId()).as("check contractId").isEqualTo(expected.getContractId()))
            .satisfies(a -> assertThat(a.getClauseNumber()).as("check clauseNumber").isEqualTo(expected.getClauseNumber()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getClauseType()).as("check clauseType").isEqualTo(expected.getClauseType()))
            .satisfies(a -> assertThat(a.getIsMandatory()).as("check isMandatory").isEqualTo(expected.getIsMandatory()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractClauseUpdatableRelationshipsEquals(ContractClause expected, ContractClause actual) {
        assertThat(actual)
            .as("Verify ContractClause relationships")
            .satisfies(a -> assertThat(a.getContract()).as("check contract").isEqualTo(expected.getContract()));
    }
}
