package fr.smartprod.paperdms.business.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InvoiceLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceLineAllPropertiesEquals(InvoiceLine expected, InvoiceLine actual) {
        assertInvoiceLineAutoGeneratedPropertiesEquals(expected, actual);
        assertInvoiceLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceLineAllUpdatablePropertiesEquals(InvoiceLine expected, InvoiceLine actual) {
        assertInvoiceLineUpdatableFieldsEquals(expected, actual);
        assertInvoiceLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceLineAutoGeneratedPropertiesEquals(InvoiceLine expected, InvoiceLine actual) {
        assertThat(actual)
            .as("Verify InvoiceLine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceLineUpdatableFieldsEquals(InvoiceLine expected, InvoiceLine actual) {
        assertThat(actual)
            .as("Verify InvoiceLine relevant properties")
            .satisfies(a -> assertThat(a.getInvoiceId()).as("check invoiceId").isEqualTo(expected.getInvoiceId()))
            .satisfies(a -> assertThat(a.getLineNumber()).as("check lineNumber").isEqualTo(expected.getLineNumber()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a -> assertThat(a.getUnitPrice()).as("check unitPrice").isEqualTo(expected.getUnitPrice()))
            .satisfies(a -> assertThat(a.getTaxRate()).as("check taxRate").isEqualTo(expected.getTaxRate()))
            .satisfies(a ->
                assertThat(a.getTotalAmountExclTax()).as("check totalAmountExclTax").isEqualTo(expected.getTotalAmountExclTax())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoiceLineUpdatableRelationshipsEquals(InvoiceLine expected, InvoiceLine actual) {
        assertThat(actual)
            .as("Verify InvoiceLine relationships")
            .satisfies(a -> assertThat(a.getInvoice()).as("check invoice").isEqualTo(expected.getInvoice()));
    }
}
