package fr.smartprod.paperdms.business.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ManualChapterAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManualChapterAllPropertiesEquals(ManualChapter expected, ManualChapter actual) {
        assertManualChapterAutoGeneratedPropertiesEquals(expected, actual);
        assertManualChapterAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManualChapterAllUpdatablePropertiesEquals(ManualChapter expected, ManualChapter actual) {
        assertManualChapterUpdatableFieldsEquals(expected, actual);
        assertManualChapterUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManualChapterAutoGeneratedPropertiesEquals(ManualChapter expected, ManualChapter actual) {
        assertThat(actual)
            .as("Verify ManualChapter auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManualChapterUpdatableFieldsEquals(ManualChapter expected, ManualChapter actual) {
        assertThat(actual)
            .as("Verify ManualChapter relevant properties")
            .satisfies(a -> assertThat(a.getManualId()).as("check manualId").isEqualTo(expected.getManualId()))
            .satisfies(a -> assertThat(a.getChapterNumber()).as("check chapterNumber").isEqualTo(expected.getChapterNumber()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getPageStart()).as("check pageStart").isEqualTo(expected.getPageStart()))
            .satisfies(a -> assertThat(a.getPageEnd()).as("check pageEnd").isEqualTo(expected.getPageEnd()))
            .satisfies(a -> assertThat(a.getLevel()).as("check level").isEqualTo(expected.getLevel()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManualChapterUpdatableRelationshipsEquals(ManualChapter expected, ManualChapter actual) {
        assertThat(actual)
            .as("Verify ManualChapter relationships")
            .satisfies(a -> assertThat(a.getManual()).as("check manual").isEqualTo(expected.getManual()))
            .satisfies(a -> assertThat(a.getParentChapter()).as("check parentChapter").isEqualTo(expected.getParentChapter()));
    }
}
