package fr.smartprod.paperdms.business.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ManualAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManualAllPropertiesEquals(Manual expected, Manual actual) {
        assertManualAutoGeneratedPropertiesEquals(expected, actual);
        assertManualAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManualAllUpdatablePropertiesEquals(Manual expected, Manual actual) {
        assertManualUpdatableFieldsEquals(expected, actual);
        assertManualUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManualAutoGeneratedPropertiesEquals(Manual expected, Manual actual) {
        assertThat(actual)
            .as("Verify Manual auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManualUpdatableFieldsEquals(Manual expected, Manual actual) {
        assertThat(actual)
            .as("Verify Manual relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getManualType()).as("check manualType").isEqualTo(expected.getManualType()))
            .satisfies(a -> assertThat(a.getVersion()).as("check version").isEqualTo(expected.getVersion()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()))
            .satisfies(a -> assertThat(a.getPublicationDate()).as("check publicationDate").isEqualTo(expected.getPublicationDate()))
            .satisfies(a -> assertThat(a.getPageCount()).as("check pageCount").isEqualTo(expected.getPageCount()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getIsPublic()).as("check isPublic").isEqualTo(expected.getIsPublic()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManualUpdatableRelationshipsEquals(Manual expected, Manual actual) {
        // empty method
    }
}
