package fr.smartprod.paperdms.ocr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExtractedTextAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExtractedTextAllPropertiesEquals(ExtractedText expected, ExtractedText actual) {
        assertExtractedTextAutoGeneratedPropertiesEquals(expected, actual);
        assertExtractedTextAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExtractedTextAllUpdatablePropertiesEquals(ExtractedText expected, ExtractedText actual) {
        assertExtractedTextUpdatableFieldsEquals(expected, actual);
        assertExtractedTextUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExtractedTextAutoGeneratedPropertiesEquals(ExtractedText expected, ExtractedText actual) {
        assertThat(actual)
            .as("Verify ExtractedText auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExtractedTextUpdatableFieldsEquals(ExtractedText expected, ExtractedText actual) {
        assertThat(actual)
            .as("Verify ExtractedText relevant properties")
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getContentSha256()).as("check contentSha256").isEqualTo(expected.getContentSha256()))
            .satisfies(a -> assertThat(a.gets3ContentKey()).as("check s3ContentKey").isEqualTo(expected.gets3ContentKey()))
            .satisfies(a -> assertThat(a.gets3Bucket()).as("check s3Bucket").isEqualTo(expected.gets3Bucket()))
            .satisfies(a -> assertThat(a.getPageNumber()).as("check pageNumber").isEqualTo(expected.getPageNumber()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()))
            .satisfies(a -> assertThat(a.getWordCount()).as("check wordCount").isEqualTo(expected.getWordCount()))
            .satisfies(a -> assertThat(a.getHasStructuredData()).as("check hasStructuredData").isEqualTo(expected.getHasStructuredData()))
            .satisfies(a -> assertThat(a.getStructuredData()).as("check structuredData").isEqualTo(expected.getStructuredData()))
            .satisfies(a ->
                assertThat(a.getStructuredDataS3Key()).as("check structuredDataS3Key").isEqualTo(expected.getStructuredDataS3Key())
            )
            .satisfies(a -> assertThat(a.getExtractedDate()).as("check extractedDate").isEqualTo(expected.getExtractedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExtractedTextUpdatableRelationshipsEquals(ExtractedText expected, ExtractedText actual) {
        assertThat(actual)
            .as("Verify ExtractedText relationships")
            .satisfies(a -> assertThat(a.getJob()).as("check job").isEqualTo(expected.getJob()));
    }
}
