package fr.smartprod.paperdms.ocr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OcrCacheAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrCacheAllPropertiesEquals(OcrCache expected, OcrCache actual) {
        assertOcrCacheAutoGeneratedPropertiesEquals(expected, actual);
        assertOcrCacheAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrCacheAllUpdatablePropertiesEquals(OcrCache expected, OcrCache actual) {
        assertOcrCacheUpdatableFieldsEquals(expected, actual);
        assertOcrCacheUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrCacheAutoGeneratedPropertiesEquals(OcrCache expected, OcrCache actual) {
        assertThat(actual)
            .as("Verify OcrCache auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrCacheUpdatableFieldsEquals(OcrCache expected, OcrCache actual) {
        assertThat(actual)
            .as("Verify OcrCache relevant properties")
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()))
            .satisfies(a -> assertThat(a.getOcrEngine()).as("check ocrEngine").isEqualTo(expected.getOcrEngine()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()))
            .satisfies(a -> assertThat(a.getPageCount()).as("check pageCount").isEqualTo(expected.getPageCount()))
            .satisfies(a -> assertThat(a.getTotalConfidence()).as("check totalConfidence").isEqualTo(expected.getTotalConfidence()))
            .satisfies(a -> assertThat(a.gets3ResultKey()).as("check s3ResultKey").isEqualTo(expected.gets3ResultKey()))
            .satisfies(a -> assertThat(a.gets3Bucket()).as("check s3Bucket").isEqualTo(expected.gets3Bucket()))
            .satisfies(a -> assertThat(a.getExtractedTextS3Key()).as("check extractedTextS3Key").isEqualTo(expected.getExtractedTextS3Key())
            )
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()))
            .satisfies(a -> assertThat(a.getHits()).as("check hits").isEqualTo(expected.getHits()))
            .satisfies(a -> assertThat(a.getLastAccessDate()).as("check lastAccessDate").isEqualTo(expected.getLastAccessDate()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getExpirationDate()).as("check expirationDate").isEqualTo(expected.getExpirationDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrCacheUpdatableRelationshipsEquals(OcrCache expected, OcrCache actual) {
        // empty method
    }
}
