package fr.smartprod.paperdms.ocr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OcrComparisonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrComparisonAllPropertiesEquals(OcrComparison expected, OcrComparison actual) {
        assertOcrComparisonAutoGeneratedPropertiesEquals(expected, actual);
        assertOcrComparisonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrComparisonAllUpdatablePropertiesEquals(OcrComparison expected, OcrComparison actual) {
        assertOcrComparisonUpdatableFieldsEquals(expected, actual);
        assertOcrComparisonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrComparisonAutoGeneratedPropertiesEquals(OcrComparison expected, OcrComparison actual) {
        assertThat(actual)
            .as("Verify OcrComparison auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrComparisonUpdatableFieldsEquals(OcrComparison expected, OcrComparison actual) {
        assertThat(actual)
            .as("Verify OcrComparison relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()))
            .satisfies(a -> assertThat(a.getPageNumber()).as("check pageNumber").isEqualTo(expected.getPageNumber()))
            .satisfies(a -> assertThat(a.getTikaText()).as("check tikaText").isEqualTo(expected.getTikaText()))
            .satisfies(a -> assertThat(a.getTikaConfidence()).as("check tikaConfidence").isEqualTo(expected.getTikaConfidence()))
            .satisfies(a -> assertThat(a.getAiText()).as("check aiText").isEqualTo(expected.getAiText()))
            .satisfies(a -> assertThat(a.getAiConfidence()).as("check aiConfidence").isEqualTo(expected.getAiConfidence()))
            .satisfies(a -> assertThat(a.getSimilarity()).as("check similarity").isEqualTo(expected.getSimilarity()))
            .satisfies(a -> assertThat(a.getDifferences()).as("check differences").isEqualTo(expected.getDifferences()))
            .satisfies(a -> assertThat(a.getDifferencesS3Key()).as("check differencesS3Key").isEqualTo(expected.getDifferencesS3Key()))
            .satisfies(a -> assertThat(a.getSelectedEngine()).as("check selectedEngine").isEqualTo(expected.getSelectedEngine()))
            .satisfies(a -> assertThat(a.getSelectedBy()).as("check selectedBy").isEqualTo(expected.getSelectedBy()))
            .satisfies(a -> assertThat(a.getSelectedDate()).as("check selectedDate").isEqualTo(expected.getSelectedDate()))
            .satisfies(a -> assertThat(a.getComparisonDate()).as("check comparisonDate").isEqualTo(expected.getComparisonDate()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrComparisonUpdatableRelationshipsEquals(OcrComparison expected, OcrComparison actual) {
        // empty method
    }
}
