package fr.smartprod.paperdms.ocr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OcrJobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrJobAllPropertiesEquals(OcrJob expected, OcrJob actual) {
        assertOcrJobAutoGeneratedPropertiesEquals(expected, actual);
        assertOcrJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrJobAllUpdatablePropertiesEquals(OcrJob expected, OcrJob actual) {
        assertOcrJobUpdatableFieldsEquals(expected, actual);
        assertOcrJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrJobAutoGeneratedPropertiesEquals(OcrJob expected, OcrJob actual) {
        assertThat(actual)
            .as("Verify OcrJob auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrJobUpdatableFieldsEquals(OcrJob expected, OcrJob actual) {
        assertThat(actual)
            .as("Verify OcrJob relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()))
            .satisfies(a -> assertThat(a.gets3Key()).as("check s3Key").isEqualTo(expected.gets3Key()))
            .satisfies(a -> assertThat(a.gets3Bucket()).as("check s3Bucket").isEqualTo(expected.gets3Bucket()))
            .satisfies(a -> assertThat(a.getRequestedLanguage()).as("check requestedLanguage").isEqualTo(expected.getRequestedLanguage()))
            .satisfies(a -> assertThat(a.getDetectedLanguage()).as("check detectedLanguage").isEqualTo(expected.getDetectedLanguage()))
            .satisfies(a -> assertThat(a.getLanguageConfidence()).as("check languageConfidence").isEqualTo(expected.getLanguageConfidence())
            )
            .satisfies(a -> assertThat(a.getOcrEngine()).as("check ocrEngine").isEqualTo(expected.getOcrEngine()))
            .satisfies(a -> assertThat(a.getTikaEndpoint()).as("check tikaEndpoint").isEqualTo(expected.getTikaEndpoint()))
            .satisfies(a -> assertThat(a.getAiProvider()).as("check aiProvider").isEqualTo(expected.getAiProvider()))
            .satisfies(a -> assertThat(a.getAiModel()).as("check aiModel").isEqualTo(expected.getAiModel()))
            .satisfies(a -> assertThat(a.getResultCacheKey()).as("check resultCacheKey").isEqualTo(expected.getResultCacheKey()))
            .satisfies(a -> assertThat(a.getIsCached()).as("check isCached").isEqualTo(expected.getIsCached()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getPageCount()).as("check pageCount").isEqualTo(expected.getPageCount()))
            .satisfies(a -> assertThat(a.getProgress()).as("check progress").isEqualTo(expected.getProgress()))
            .satisfies(a -> assertThat(a.getRetryCount()).as("check retryCount").isEqualTo(expected.getRetryCount()))
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()))
            .satisfies(a -> assertThat(a.getProcessingTime()).as("check processingTime").isEqualTo(expected.getProcessingTime()))
            .satisfies(a -> assertThat(a.getCostEstimate()).as("check costEstimate").isEqualTo(expected.getCostEstimate()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOcrJobUpdatableRelationshipsEquals(OcrJob expected, OcrJob actual) {
        // empty method
    }
}
