package fr.smartprod.paperdms.ocr.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrcExtractedTextAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrcExtractedTextAllPropertiesEquals(OrcExtractedText expected, OrcExtractedText actual) {
        assertOrcExtractedTextAutoGeneratedPropertiesEquals(expected, actual);
        assertOrcExtractedTextAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrcExtractedTextAllUpdatablePropertiesEquals(OrcExtractedText expected, OrcExtractedText actual) {
        assertOrcExtractedTextUpdatableFieldsEquals(expected, actual);
        assertOrcExtractedTextUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrcExtractedTextAutoGeneratedPropertiesEquals(OrcExtractedText expected, OrcExtractedText actual) {
        assertThat(actual)
            .as("Verify OrcExtractedText auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrcExtractedTextUpdatableFieldsEquals(OrcExtractedText expected, OrcExtractedText actual) {
        assertThat(actual)
            .as("Verify OrcExtractedText relevant properties")
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getContentSha256()).as("check contentSha256").isEqualTo(expected.getContentSha256()))
            .satisfies(a -> assertThat(a.gets3ContentKey()).as("check s3ContentKey").isEqualTo(expected.gets3ContentKey()))
            .satisfies(a -> assertThat(a.gets3Bucket()).as("check s3Bucket").isEqualTo(expected.gets3Bucket()))
            .satisfies(a -> assertThat(a.getPageNumber()).as("check pageNumber").isEqualTo(expected.getPageNumber()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()))
            .satisfies(a -> assertThat(a.getWordCount()).as("check wordCount").isEqualTo(expected.getWordCount()))
            .satisfies(a -> assertThat(a.getHasStructuredData()).as("check hasStructuredData").isEqualTo(expected.getHasStructuredData()))
            .satisfies(a -> assertThat(a.getStructuredData()).as("check structuredData").isEqualTo(expected.getStructuredData()))
            .satisfies(a ->
                assertThat(a.getStructuredDataS3Key()).as("check structuredDataS3Key").isEqualTo(expected.getStructuredDataS3Key())
            )
            .satisfies(a -> assertThat(a.getExtractedDate()).as("check extractedDate").isEqualTo(expected.getExtractedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrcExtractedTextUpdatableRelationshipsEquals(OrcExtractedText expected, OrcExtractedText actual) {
        assertThat(actual)
            .as("Verify OrcExtractedText relationships")
            .satisfies(a -> assertThat(a.getJob()).as("check job").isEqualTo(expected.getJob()));
    }
}
