export enum ClauseType {
  GENERAL = 'GENERAL',

  PAYMENT = 'PAYMENT',

  TERMINATION = 'TERMINATION',

  CONFIDENTIALITY = 'CONFIDENTIALITY',

  LIABILITY = 'LIABILITY',

  DISPUTE_RESOLUTION = 'DISPUTE_RESOLUTION',

  INTELLECTUAL_PROPERTY = 'INTELLECTUAL_PROPERTY',

  WARRANTY = 'WARRANTY',

  FORCE_MAJEURE = 'FORCE_MAJEURE',

  AMENDMENT = 'AMENDMENT',
}
