export enum ContractStatus {
  DRAFT = 'DRAFT',

  UNDER_NEGOTIATION = 'UNDER_NEGOTIATION',

  PENDING_SIGNATURE = 'PENDING_SIGNATURE',

  ACTIVE = 'ACTIVE',

  SUSPENDED = 'SUSPENDED',

  EXPIRED = 'EXPIRED',

  TERMINATED = 'TERMINATED',

  RENEWED = 'RENEWED',

  ARCHIVED = 'ARCHIVED',
}
