export enum ManualType {
  USER_MANUAL = 'USER_MANUAL',

  TECHNICAL_MANUAL = 'TECHNICAL_MANUAL',

  INSTALLATION_GUIDE = 'INSTALLATION_GUIDE',

  MAINTENANCE_GUIDE = 'MAINTENANCE_GUIDE',

  TRAINING_MATERIAL = 'TRAINING_MATERIAL',

  POLICY_DOCUMENT = 'POLICY_DOCUMENT',

  PROCEDURE = 'PROCEDURE',

  STANDARD = 'STANDARD',

  SPECIFICATION = 'SPECIFICATION',
}
