export enum WidgetType {
  DOCUMENT_COUNT = 'DOCUMENT_COUNT',

  STORAGE_USAGE = 'STORAGE_USAGE',

  RECENT_UPLOADS = 'RECENT_UPLOADS',

  TOP_TAGS = 'TOP_TAGS',

  WORKFLOW_STATUS = 'WORKFLOW_STATUS',

  USER_ACTIVITY = 'USER_ACTIVITY',

  CHART_LINE = 'CHART_LINE',

  CHART_BAR = 'CHART_BAR',

  CHART_PIE = 'CHART_PIE',

  CHART_DOUGHNUT = 'CHART_DOUGHNUT',

  CHART_AREA = 'CHART_AREA',

  TABLE = 'TABLE',

  METRIC = 'METRIC',

  HEATMAP = 'HEATMAP',

  GAUGE = 'GAUGE',

  TIMELINE = 'TIMELINE',
}
