package fr.smartprod.paperdms.similarity.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SimilarityDocumentFingerprintAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityDocumentFingerprintAllPropertiesEquals(
        SimilarityDocumentFingerprint expected,
        SimilarityDocumentFingerprint actual
    ) {
        assertSimilarityDocumentFingerprintAutoGeneratedPropertiesEquals(expected, actual);
        assertSimilarityDocumentFingerprintAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityDocumentFingerprintAllUpdatablePropertiesEquals(
        SimilarityDocumentFingerprint expected,
        SimilarityDocumentFingerprint actual
    ) {
        assertSimilarityDocumentFingerprintUpdatableFieldsEquals(expected, actual);
        assertSimilarityDocumentFingerprintUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityDocumentFingerprintAutoGeneratedPropertiesEquals(
        SimilarityDocumentFingerprint expected,
        SimilarityDocumentFingerprint actual
    ) {
        assertThat(actual)
            .as("Verify SimilarityDocumentFingerprint auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityDocumentFingerprintUpdatableFieldsEquals(
        SimilarityDocumentFingerprint expected,
        SimilarityDocumentFingerprint actual
    ) {
        assertThat(actual)
            .as("Verify SimilarityDocumentFingerprint relevant properties")
            .satisfies(a -> assertThat(a.getFingerprintType()).as("check fingerprintType").isEqualTo(expected.getFingerprintType()))
            .satisfies(a -> assertThat(a.getFingerprint()).as("check fingerprint").isEqualTo(expected.getFingerprint()))
            .satisfies(a -> assertThat(a.getVectorEmbedding()).as("check vectorEmbedding").isEqualTo(expected.getVectorEmbedding()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()))
            .satisfies(a -> assertThat(a.getComputedDate()).as("check computedDate").isEqualTo(expected.getComputedDate()))
            .satisfies(a -> assertThat(a.getLastUpdated()).as("check lastUpdated").isEqualTo(expected.getLastUpdated()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityDocumentFingerprintUpdatableRelationshipsEquals(
        SimilarityDocumentFingerprint expected,
        SimilarityDocumentFingerprint actual
    ) {
        // empty method
    }
}
