package fr.smartprod.paperdms.similarity.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SimilarityDocumentComparisonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityDocumentComparisonAllPropertiesEquals(
        SimilarityDocumentComparison expected,
        SimilarityDocumentComparison actual
    ) {
        assertSimilarityDocumentComparisonAutoGeneratedPropertiesEquals(expected, actual);
        assertSimilarityDocumentComparisonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityDocumentComparisonAllUpdatablePropertiesEquals(
        SimilarityDocumentComparison expected,
        SimilarityDocumentComparison actual
    ) {
        assertSimilarityDocumentComparisonUpdatableFieldsEquals(expected, actual);
        assertSimilarityDocumentComparisonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityDocumentComparisonAutoGeneratedPropertiesEquals(
        SimilarityDocumentComparison expected,
        SimilarityDocumentComparison actual
    ) {
        assertThat(actual)
            .as("Verify SimilarityDocumentComparison auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityDocumentComparisonUpdatableFieldsEquals(
        SimilarityDocumentComparison expected,
        SimilarityDocumentComparison actual
    ) {
        assertThat(actual)
            .as("Verify SimilarityDocumentComparison relevant properties")
            .satisfies(a ->
                assertThat(a.getSourceDocumentSha256()).as("check sourceDocumentSha256").isEqualTo(expected.getSourceDocumentSha256())
            )
            .satisfies(a ->
                assertThat(a.getTargetDocumentSha256()).as("check targetDocumentSha256").isEqualTo(expected.getTargetDocumentSha256())
            )
            .satisfies(a -> assertThat(a.getSimilarityScore()).as("check similarityScore").isEqualTo(expected.getSimilarityScore()))
            .satisfies(a -> assertThat(a.getAlgorithm()).as("check algorithm").isEqualTo(expected.getAlgorithm()))
            .satisfies(a -> assertThat(a.getFeatures()).as("check features").isEqualTo(expected.getFeatures()))
            .satisfies(a -> assertThat(a.getComputedDate()).as("check computedDate").isEqualTo(expected.getComputedDate()))
            .satisfies(a -> assertThat(a.getIsRelevant()).as("check isRelevant").isEqualTo(expected.getIsRelevant()))
            .satisfies(a -> assertThat(a.getReviewedBy()).as("check reviewedBy").isEqualTo(expected.getReviewedBy()))
            .satisfies(a -> assertThat(a.getReviewedDate()).as("check reviewedDate").isEqualTo(expected.getReviewedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityDocumentComparisonUpdatableRelationshipsEquals(
        SimilarityDocumentComparison expected,
        SimilarityDocumentComparison actual
    ) {
        assertThat(actual)
            .as("Verify SimilarityDocumentComparison relationships")
            .satisfies(a -> assertThat(a.getJob()).as("check job").isEqualTo(expected.getJob()));
    }
}
