package fr.smartprod.paperdms.similarity.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SimilarityClusterAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityClusterAllPropertiesEquals(SimilarityCluster expected, SimilarityCluster actual) {
        assertSimilarityClusterAutoGeneratedPropertiesEquals(expected, actual);
        assertSimilarityClusterAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityClusterAllUpdatablePropertiesEquals(SimilarityCluster expected, SimilarityCluster actual) {
        assertSimilarityClusterUpdatableFieldsEquals(expected, actual);
        assertSimilarityClusterUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityClusterAutoGeneratedPropertiesEquals(SimilarityCluster expected, SimilarityCluster actual) {
        assertThat(actual)
            .as("Verify SimilarityCluster auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityClusterUpdatableFieldsEquals(SimilarityCluster expected, SimilarityCluster actual) {
        assertThat(actual)
            .as("Verify SimilarityCluster relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getAlgorithm()).as("check algorithm").isEqualTo(expected.getAlgorithm()))
            .satisfies(a -> assertThat(a.getCentroid()).as("check centroid").isEqualTo(expected.getCentroid()))
            .satisfies(a -> assertThat(a.getDocumentCount()).as("check documentCount").isEqualTo(expected.getDocumentCount()))
            .satisfies(a -> assertThat(a.getAvgSimilarity()).as("check avgSimilarity").isEqualTo(expected.getAvgSimilarity()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastUpdated()).as("check lastUpdated").isEqualTo(expected.getLastUpdated()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSimilarityClusterUpdatableRelationshipsEquals(SimilarityCluster expected, SimilarityCluster actual) {
        // empty method
    }
}
