package fr.smartprod.paperdms.ai.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AIAutoTagJobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAIAutoTagJobAllPropertiesEquals(AIAutoTagJob expected, AIAutoTagJob actual) {
        assertAIAutoTagJobAutoGeneratedPropertiesEquals(expected, actual);
        assertAIAutoTagJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAIAutoTagJobAllUpdatablePropertiesEquals(AIAutoTagJob expected, AIAutoTagJob actual) {
        assertAIAutoTagJobUpdatableFieldsEquals(expected, actual);
        assertAIAutoTagJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAIAutoTagJobAutoGeneratedPropertiesEquals(AIAutoTagJob expected, AIAutoTagJob actual) {
        assertThat(actual)
            .as("Verify AIAutoTagJob auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAIAutoTagJobUpdatableFieldsEquals(AIAutoTagJob expected, AIAutoTagJob actual) {
        assertThat(actual)
            .as("Verify AIAutoTagJob relevant properties")
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()))
            .satisfies(a -> assertThat(a.gets3Key()).as("check s3Key").isEqualTo(expected.gets3Key()))
            .satisfies(a -> assertThat(a.getExtractedText()).as("check extractedText").isEqualTo(expected.getExtractedText()))
            .satisfies(a ->
                assertThat(a.getExtractedTextSha256()).as("check extractedTextSha256").isEqualTo(expected.getExtractedTextSha256())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getModelVersion()).as("check modelVersion").isEqualTo(expected.getModelVersion()))
            .satisfies(a -> assertThat(a.getResultCacheKey()).as("check resultCacheKey").isEqualTo(expected.getResultCacheKey()))
            .satisfies(a -> assertThat(a.getIsCached()).as("check isCached").isEqualTo(expected.getIsCached()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAIAutoTagJobUpdatableRelationshipsEquals(AIAutoTagJob expected, AIAutoTagJob actual) {
        assertThat(actual)
            .as("Verify AIAutoTagJob relationships")
            .satisfies(a -> assertThat(a.getaITypePrediction()).as("check aITypePrediction").isEqualTo(expected.getaITypePrediction()))
            .satisfies(a -> assertThat(a.getLanguagePrediction()).as("check languagePrediction").isEqualTo(expected.getLanguagePrediction())
            );
    }
}
