package fr.smartprod.paperdms.ai.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AiCacheAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiCacheAllPropertiesEquals(AiCache expected, AiCache actual) {
        assertAiCacheAutoGeneratedPropertiesEquals(expected, actual);
        assertAiCacheAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiCacheAllUpdatablePropertiesEquals(AiCache expected, AiCache actual) {
        assertAiCacheUpdatableFieldsEquals(expected, actual);
        assertAiCacheUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiCacheAutoGeneratedPropertiesEquals(AiCache expected, AiCache actual) {
        assertThat(actual)
            .as("Verify AiCache auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiCacheUpdatableFieldsEquals(AiCache expected, AiCache actual) {
        assertThat(actual)
            .as("Verify AiCache relevant properties")
            .satisfies(a -> assertThat(a.getCacheKey()).as("check cacheKey").isEqualTo(expected.getCacheKey()))
            .satisfies(a -> assertThat(a.getInputSha256()).as("check inputSha256").isEqualTo(expected.getInputSha256()))
            .satisfies(a -> assertThat(a.getAiProvider()).as("check aiProvider").isEqualTo(expected.getAiProvider()))
            .satisfies(a -> assertThat(a.getAiModel()).as("check aiModel").isEqualTo(expected.getAiModel()))
            .satisfies(a -> assertThat(a.getOperation()).as("check operation").isEqualTo(expected.getOperation()))
            .satisfies(a -> assertThat(a.getInputData()).as("check inputData").isEqualTo(expected.getInputData()))
            .satisfies(a -> assertThat(a.getResultData()).as("check resultData").isEqualTo(expected.getResultData()))
            .satisfies(a -> assertThat(a.gets3ResultKey()).as("check s3ResultKey").isEqualTo(expected.gets3ResultKey()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()))
            .satisfies(a -> assertThat(a.getHits()).as("check hits").isEqualTo(expected.getHits()))
            .satisfies(a -> assertThat(a.getCost()).as("check cost").isEqualTo(expected.getCost()))
            .satisfies(a -> assertThat(a.getLastAccessDate()).as("check lastAccessDate").isEqualTo(expected.getLastAccessDate()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getExpirationDate()).as("check expirationDate").isEqualTo(expected.getExpirationDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAiCacheUpdatableRelationshipsEquals(AiCache expected, AiCache actual) {
        // empty method
    }
}
