package fr.smartprod.paperdms.ai.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AILanguageDetectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAILanguageDetectionAllPropertiesEquals(AILanguageDetection expected, AILanguageDetection actual) {
        assertAILanguageDetectionAutoGeneratedPropertiesEquals(expected, actual);
        assertAILanguageDetectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAILanguageDetectionAllUpdatablePropertiesEquals(AILanguageDetection expected, AILanguageDetection actual) {
        assertAILanguageDetectionUpdatableFieldsEquals(expected, actual);
        assertAILanguageDetectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAILanguageDetectionAutoGeneratedPropertiesEquals(AILanguageDetection expected, AILanguageDetection actual) {
        assertThat(actual)
            .as("Verify AILanguageDetection auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAILanguageDetectionUpdatableFieldsEquals(AILanguageDetection expected, AILanguageDetection actual) {
        assertThat(actual)
            .as("Verify AILanguageDetection relevant properties")
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()))
            .satisfies(a -> assertThat(a.getDetectedLanguage()).as("check detectedLanguage").isEqualTo(expected.getDetectedLanguage()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.getDetectionMethod()).as("check detectionMethod").isEqualTo(expected.getDetectionMethod()))
            .satisfies(a ->
                assertThat(a.getAlternativeLanguages()).as("check alternativeLanguages").isEqualTo(expected.getAlternativeLanguages())
            )
            .satisfies(a -> assertThat(a.getTextSample()).as("check textSample").isEqualTo(expected.getTextSample()))
            .satisfies(a -> assertThat(a.getResultCacheKey()).as("check resultCacheKey").isEqualTo(expected.getResultCacheKey()))
            .satisfies(a -> assertThat(a.getIsCached()).as("check isCached").isEqualTo(expected.getIsCached()))
            .satisfies(a -> assertThat(a.getDetectedDate()).as("check detectedDate").isEqualTo(expected.getDetectedDate()))
            .satisfies(a -> assertThat(a.getModelVersion()).as("check modelVersion").isEqualTo(expected.getModelVersion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAILanguageDetectionUpdatableRelationshipsEquals(AILanguageDetection expected, AILanguageDetection actual) {
        // empty method
    }
}
