package fr.smartprod.paperdms.ai.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AITagPredictionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAITagPredictionAllPropertiesEquals(AITagPrediction expected, AITagPrediction actual) {
        assertAITagPredictionAutoGeneratedPropertiesEquals(expected, actual);
        assertAITagPredictionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAITagPredictionAllUpdatablePropertiesEquals(AITagPrediction expected, AITagPrediction actual) {
        assertAITagPredictionUpdatableFieldsEquals(expected, actual);
        assertAITagPredictionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAITagPredictionAutoGeneratedPropertiesEquals(AITagPrediction expected, AITagPrediction actual) {
        assertThat(actual)
            .as("Verify AITagPrediction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAITagPredictionUpdatableFieldsEquals(AITagPrediction expected, AITagPrediction actual) {
        assertThat(actual)
            .as("Verify AITagPrediction relevant properties")
            .satisfies(a -> assertThat(a.getTagName()).as("check tagName").isEqualTo(expected.getTagName()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getModelVersion()).as("check modelVersion").isEqualTo(expected.getModelVersion()))
            .satisfies(a -> assertThat(a.getPredictionS3Key()).as("check predictionS3Key").isEqualTo(expected.getPredictionS3Key()))
            .satisfies(a -> assertThat(a.getIsAccepted()).as("check isAccepted").isEqualTo(expected.getIsAccepted()))
            .satisfies(a -> assertThat(a.getAcceptedBy()).as("check acceptedBy").isEqualTo(expected.getAcceptedBy()))
            .satisfies(a -> assertThat(a.getAcceptedDate()).as("check acceptedDate").isEqualTo(expected.getAcceptedDate()))
            .satisfies(a -> assertThat(a.getPredictionDate()).as("check predictionDate").isEqualTo(expected.getPredictionDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAITagPredictionUpdatableRelationshipsEquals(AITagPrediction expected, AITagPrediction actual) {
        assertThat(actual)
            .as("Verify AITagPrediction relationships")
            .satisfies(a -> assertThat(a.getJob()).as("check job").isEqualTo(expected.getJob()));
    }
}
