package fr.smartprod.paperdms.ai.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LanguageDetectionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLanguageDetectionAllPropertiesEquals(LanguageDetection expected, LanguageDetection actual) {
        assertLanguageDetectionAutoGeneratedPropertiesEquals(expected, actual);
        assertLanguageDetectionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLanguageDetectionAllUpdatablePropertiesEquals(LanguageDetection expected, LanguageDetection actual) {
        assertLanguageDetectionUpdatableFieldsEquals(expected, actual);
        assertLanguageDetectionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLanguageDetectionAutoGeneratedPropertiesEquals(LanguageDetection expected, LanguageDetection actual) {
        assertThat(actual)
            .as("Verify LanguageDetection auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLanguageDetectionUpdatableFieldsEquals(LanguageDetection expected, LanguageDetection actual) {
        assertThat(actual)
            .as("Verify LanguageDetection relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()))
            .satisfies(a -> assertThat(a.getDetectedLanguage()).as("check detectedLanguage").isEqualTo(expected.getDetectedLanguage()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.getDetectionMethod()).as("check detectionMethod").isEqualTo(expected.getDetectionMethod()))
            .satisfies(a ->
                assertThat(a.getAlternativeLanguages()).as("check alternativeLanguages").isEqualTo(expected.getAlternativeLanguages())
            )
            .satisfies(a -> assertThat(a.getTextSample()).as("check textSample").isEqualTo(expected.getTextSample()))
            .satisfies(a -> assertThat(a.getResultCacheKey()).as("check resultCacheKey").isEqualTo(expected.getResultCacheKey()))
            .satisfies(a -> assertThat(a.getIsCached()).as("check isCached").isEqualTo(expected.getIsCached()))
            .satisfies(a -> assertThat(a.getDetectedDate()).as("check detectedDate").isEqualTo(expected.getDetectedDate()))
            .satisfies(a -> assertThat(a.getModelVersion()).as("check modelVersion").isEqualTo(expected.getModelVersion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLanguageDetectionUpdatableRelationshipsEquals(LanguageDetection expected, LanguageDetection actual) {
        // empty method
    }
}
