package fr.smartprod.paperdms.ai.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TagPredictionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTagPredictionAllPropertiesEquals(TagPrediction expected, TagPrediction actual) {
        assertTagPredictionAutoGeneratedPropertiesEquals(expected, actual);
        assertTagPredictionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTagPredictionAllUpdatablePropertiesEquals(TagPrediction expected, TagPrediction actual) {
        assertTagPredictionUpdatableFieldsEquals(expected, actual);
        assertTagPredictionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTagPredictionAutoGeneratedPropertiesEquals(TagPrediction expected, TagPrediction actual) {
        assertThat(actual)
            .as("Verify TagPrediction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTagPredictionUpdatableFieldsEquals(TagPrediction expected, TagPrediction actual) {
        assertThat(actual)
            .as("Verify TagPrediction relevant properties")
            .satisfies(a -> assertThat(a.getTagName()).as("check tagName").isEqualTo(expected.getTagName()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getModelVersion()).as("check modelVersion").isEqualTo(expected.getModelVersion()))
            .satisfies(a -> assertThat(a.getPredictionS3Key()).as("check predictionS3Key").isEqualTo(expected.getPredictionS3Key()))
            .satisfies(a -> assertThat(a.getIsAccepted()).as("check isAccepted").isEqualTo(expected.getIsAccepted()))
            .satisfies(a -> assertThat(a.getAcceptedBy()).as("check acceptedBy").isEqualTo(expected.getAcceptedBy()))
            .satisfies(a -> assertThat(a.getAcceptedDate()).as("check acceptedDate").isEqualTo(expected.getAcceptedDate()))
            .satisfies(a -> assertThat(a.getPredictionDate()).as("check predictionDate").isEqualTo(expected.getPredictionDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTagPredictionUpdatableRelationshipsEquals(TagPrediction expected, TagPrediction actual) {
        assertThat(actual)
            .as("Verify TagPrediction relationships")
            .satisfies(a -> assertThat(a.getJob()).as("check job").isEqualTo(expected.getJob()));
    }
}
