package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BookmarkAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookmarkAllPropertiesEquals(Bookmark expected, Bookmark actual) {
        assertBookmarkAutoGeneratedPropertiesEquals(expected, actual);
        assertBookmarkAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookmarkAllUpdatablePropertiesEquals(Bookmark expected, Bookmark actual) {
        assertBookmarkUpdatableFieldsEquals(expected, actual);
        assertBookmarkUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookmarkAutoGeneratedPropertiesEquals(Bookmark expected, Bookmark actual) {
        assertThat(actual)
            .as("Verify Bookmark auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookmarkUpdatableFieldsEquals(Bookmark expected, Bookmark actual) {
        assertThat(actual)
            .as("Verify Bookmark relevant properties")
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getEntityType()).as("check entityType").isEqualTo(expected.getEntityType()))
            .satisfies(a -> assertThat(a.getEntityId()).as("check entityId").isEqualTo(expected.getEntityId()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookmarkUpdatableRelationshipsEquals(Bookmark expected, Bookmark actual) {
        // empty method
    }
}
