package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentStatisticsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentStatisticsAllPropertiesEquals(DocumentStatistics expected, DocumentStatistics actual) {
        assertDocumentStatisticsAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentStatisticsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentStatisticsAllUpdatablePropertiesEquals(DocumentStatistics expected, DocumentStatistics actual) {
        assertDocumentStatisticsUpdatableFieldsEquals(expected, actual);
        assertDocumentStatisticsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentStatisticsAutoGeneratedPropertiesEquals(DocumentStatistics expected, DocumentStatistics actual) {
        assertThat(actual)
            .as("Verify DocumentStatistics auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentStatisticsUpdatableFieldsEquals(DocumentStatistics expected, DocumentStatistics actual) {
        assertThat(actual)
            .as("Verify DocumentStatistics relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getViewsTotal()).as("check viewsTotal").isEqualTo(expected.getViewsTotal()))
            .satisfies(a -> assertThat(a.getDownloadsTotal()).as("check downloadsTotal").isEqualTo(expected.getDownloadsTotal()))
            .satisfies(a -> assertThat(a.getUniqueViewers()).as("check uniqueViewers").isEqualTo(expected.getUniqueViewers()))
            .satisfies(a -> assertThat(a.getLastUpdated()).as("check lastUpdated").isEqualTo(expected.getLastUpdated()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentStatisticsUpdatableRelationshipsEquals(DocumentStatistics expected, DocumentStatistics actual) {
        // empty method
    }
}
