package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentTemplateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTemplateAllPropertiesEquals(DocumentTemplate expected, DocumentTemplate actual) {
        assertDocumentTemplateAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentTemplateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTemplateAllUpdatablePropertiesEquals(DocumentTemplate expected, DocumentTemplate actual) {
        assertDocumentTemplateUpdatableFieldsEquals(expected, actual);
        assertDocumentTemplateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTemplateAutoGeneratedPropertiesEquals(DocumentTemplate expected, DocumentTemplate actual) {
        assertThat(actual)
            .as("Verify DocumentTemplate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTemplateUpdatableFieldsEquals(DocumentTemplate expected, DocumentTemplate actual) {
        assertThat(actual)
            .as("Verify DocumentTemplate relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getTemplateSha256()).as("check templateSha256").isEqualTo(expected.getTemplateSha256()))
            .satisfies(a -> assertThat(a.getTemplateS3Key()).as("check templateS3Key").isEqualTo(expected.getTemplateS3Key()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTemplateUpdatableRelationshipsEquals(DocumentTemplate expected, DocumentTemplate actual) {
        assertThat(actual)
            .as("Verify DocumentTemplate relationships")
            .satisfies(a -> assertThat(a.getDocumentType()).as("check documentType").isEqualTo(expected.getDocumentType()));
    }
}
