package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentTypeFieldAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTypeFieldAllPropertiesEquals(DocumentTypeField expected, DocumentTypeField actual) {
        assertDocumentTypeFieldAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentTypeFieldAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTypeFieldAllUpdatablePropertiesEquals(DocumentTypeField expected, DocumentTypeField actual) {
        assertDocumentTypeFieldUpdatableFieldsEquals(expected, actual);
        assertDocumentTypeFieldUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTypeFieldAutoGeneratedPropertiesEquals(DocumentTypeField expected, DocumentTypeField actual) {
        assertThat(actual)
            .as("Verify DocumentTypeField auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTypeFieldUpdatableFieldsEquals(DocumentTypeField expected, DocumentTypeField actual) {
        assertThat(actual)
            .as("Verify DocumentTypeField relevant properties")
            .satisfies(a -> assertThat(a.getFieldKey()).as("check fieldKey").isEqualTo(expected.getFieldKey()))
            .satisfies(a -> assertThat(a.getFieldLabel()).as("check fieldLabel").isEqualTo(expected.getFieldLabel()))
            .satisfies(a -> assertThat(a.getDataType()).as("check dataType").isEqualTo(expected.getDataType()))
            .satisfies(a -> assertThat(a.getIsRequired()).as("check isRequired").isEqualTo(expected.getIsRequired()))
            .satisfies(a -> assertThat(a.getIsSearchable()).as("check isSearchable").isEqualTo(expected.getIsSearchable()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTypeFieldUpdatableRelationshipsEquals(DocumentTypeField expected, DocumentTypeField actual) {
        assertThat(actual)
            .as("Verify DocumentTypeField relationships")
            .satisfies(a -> assertThat(a.getDocumentType()).as("check documentType").isEqualTo(expected.getDocumentType()));
    }
}
