package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentCommentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentCommentAllPropertiesEquals(DocumentComment expected, DocumentComment actual) {
        assertDocumentCommentAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentCommentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentCommentAllUpdatablePropertiesEquals(DocumentComment expected, DocumentComment actual) {
        assertDocumentCommentUpdatableFieldsEquals(expected, actual);
        assertDocumentCommentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentCommentAutoGeneratedPropertiesEquals(DocumentComment expected, DocumentComment actual) {
        assertThat(actual)
            .as("Verify DocumentComment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentCommentUpdatableFieldsEquals(DocumentComment expected, DocumentComment actual) {
        assertThat(actual)
            .as("Verify DocumentComment relevant properties")
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getPageNumber()).as("check pageNumber").isEqualTo(expected.getPageNumber()))
            .satisfies(a -> assertThat(a.getIsResolved()).as("check isResolved").isEqualTo(expected.getIsResolved()))
            .satisfies(a -> assertThat(a.getAuthorId()).as("check authorId").isEqualTo(expected.getAuthorId()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentCommentUpdatableRelationshipsEquals(DocumentComment expected, DocumentComment actual) {
        assertThat(actual)
            .as("Verify DocumentComment relationships")
            .satisfies(a -> assertThat(a.getDocument()).as("check document").isEqualTo(expected.getDocument()))
            .satisfies(a -> assertThat(a.getParentComment()).as("check parentComment").isEqualTo(expected.getParentComment()));
    }
}
