package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentPermissionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentPermissionAllPropertiesEquals(DocumentPermission expected, DocumentPermission actual) {
        assertDocumentPermissionAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentPermissionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentPermissionAllUpdatablePropertiesEquals(DocumentPermission expected, DocumentPermission actual) {
        assertDocumentPermissionUpdatableFieldsEquals(expected, actual);
        assertDocumentPermissionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentPermissionAutoGeneratedPropertiesEquals(DocumentPermission expected, DocumentPermission actual) {
        assertThat(actual)
            .as("Verify DocumentPermission auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentPermissionUpdatableFieldsEquals(DocumentPermission expected, DocumentPermission actual) {
        assertThat(actual)
            .as("Verify DocumentPermission relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getPrincipalType()).as("check principalType").isEqualTo(expected.getPrincipalType()))
            .satisfies(a -> assertThat(a.getPrincipalId()).as("check principalId").isEqualTo(expected.getPrincipalId()))
            .satisfies(a -> assertThat(a.getPermission()).as("check permission").isEqualTo(expected.getPermission()))
            .satisfies(a -> assertThat(a.getCanDelegate()).as("check canDelegate").isEqualTo(expected.getCanDelegate()))
            .satisfies(a -> assertThat(a.getGrantedBy()).as("check grantedBy").isEqualTo(expected.getGrantedBy()))
            .satisfies(a -> assertThat(a.getGrantedDate()).as("check grantedDate").isEqualTo(expected.getGrantedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentPermissionUpdatableRelationshipsEquals(DocumentPermission expected, DocumentPermission actual) {
        assertThat(actual)
            .as("Verify DocumentPermission relationships")
            .satisfies(a -> assertThat(a.getPermissionGroup()).as("check permissionGroup").isEqualTo(expected.getPermissionGroup()));
    }
}
