package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentMetadataAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentMetadataAllPropertiesEquals(DocumentMetadata expected, DocumentMetadata actual) {
        assertDocumentMetadataAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentMetadataAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentMetadataAllUpdatablePropertiesEquals(DocumentMetadata expected, DocumentMetadata actual) {
        assertDocumentMetadataUpdatableFieldsEquals(expected, actual);
        assertDocumentMetadataUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentMetadataAutoGeneratedPropertiesEquals(DocumentMetadata expected, DocumentMetadata actual) {
        assertThat(actual)
            .as("Verify DocumentMetadata auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentMetadataUpdatableFieldsEquals(DocumentMetadata expected, DocumentMetadata actual) {
        assertThat(actual)
            .as("Verify DocumentMetadata relevant properties")
            .satisfies(a -> assertThat(a.getKey()).as("check key").isEqualTo(expected.getKey()))
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getDataType()).as("check dataType").isEqualTo(expected.getDataType()))
            .satisfies(a -> assertThat(a.getIsSearchable()).as("check isSearchable").isEqualTo(expected.getIsSearchable()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentMetadataUpdatableRelationshipsEquals(DocumentMetadata expected, DocumentMetadata actual) {
        assertThat(actual)
            .as("Verify DocumentMetadata relationships")
            .satisfies(a -> assertThat(a.getDocument()).as("check document").isEqualTo(expected.getDocument()));
    }
}
