package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentExtractedFieldAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentExtractedFieldAllPropertiesEquals(DocumentExtractedField expected, DocumentExtractedField actual) {
        assertDocumentExtractedFieldAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentExtractedFieldAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentExtractedFieldAllUpdatablePropertiesEquals(
        DocumentExtractedField expected,
        DocumentExtractedField actual
    ) {
        assertDocumentExtractedFieldUpdatableFieldsEquals(expected, actual);
        assertDocumentExtractedFieldUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentExtractedFieldAutoGeneratedPropertiesEquals(
        DocumentExtractedField expected,
        DocumentExtractedField actual
    ) {
        assertThat(actual)
            .as("Verify DocumentExtractedField auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentExtractedFieldUpdatableFieldsEquals(DocumentExtractedField expected, DocumentExtractedField actual) {
        assertThat(actual)
            .as("Verify DocumentExtractedField relevant properties")
            .satisfies(a -> assertThat(a.getFieldKey()).as("check fieldKey").isEqualTo(expected.getFieldKey()))
            .satisfies(a -> assertThat(a.getFieldValue()).as("check fieldValue").isEqualTo(expected.getFieldValue()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.getExtractionMethod()).as("check extractionMethod").isEqualTo(expected.getExtractionMethod()))
            .satisfies(a -> assertThat(a.getIsVerified()).as("check isVerified").isEqualTo(expected.getIsVerified()))
            .satisfies(a -> assertThat(a.getExtractedDate()).as("check extractedDate").isEqualTo(expected.getExtractedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentExtractedFieldUpdatableRelationshipsEquals(
        DocumentExtractedField expected,
        DocumentExtractedField actual
    ) {
        assertThat(actual)
            .as("Verify DocumentExtractedField relationships")
            .satisfies(a -> assertThat(a.getDocument()).as("check document").isEqualTo(expected.getDocument()));
    }
}
