package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentAllPropertiesEquals(Document expected, Document actual) {
        assertDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentAllUpdatablePropertiesEquals(Document expected, Document actual) {
        assertDocumentUpdatableFieldsEquals(expected, actual);
        assertDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentAutoGeneratedPropertiesEquals(Document expected, Document actual) {
        assertThat(actual)
            .as("Verify Document auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentUpdatableFieldsEquals(Document expected, Document actual) {
        assertThat(actual)
            .as("Verify Document relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getFileName()).as("check fileName").isEqualTo(expected.getFileName()))
            .satisfies(a -> assertThat(a.getFileSize()).as("check fileSize").isEqualTo(expected.getFileSize()))
            .satisfies(a -> assertThat(a.getMimeType()).as("check mimeType").isEqualTo(expected.getMimeType()))
            .satisfies(a -> assertThat(a.getSha256()).as("check sha256").isEqualTo(expected.getSha256()))
            .satisfies(a -> assertThat(a.gets3Key()).as("check s3Key").isEqualTo(expected.gets3Key()))
            .satisfies(a -> assertThat(a.gets3Bucket()).as("check s3Bucket").isEqualTo(expected.gets3Bucket()))
            .satisfies(a -> assertThat(a.gets3Region()).as("check s3Region").isEqualTo(expected.gets3Region()))
            .satisfies(a -> assertThat(a.gets3Etag()).as("check s3Etag").isEqualTo(expected.gets3Etag()))
            .satisfies(a -> assertThat(a.getThumbnailS3Key()).as("check thumbnailS3Key").isEqualTo(expected.getThumbnailS3Key()))
            .satisfies(a -> assertThat(a.getThumbnailSha256()).as("check thumbnailSha256").isEqualTo(expected.getThumbnailSha256()))
            .satisfies(a -> assertThat(a.getWebpPreviewS3Key()).as("check webpPreviewS3Key").isEqualTo(expected.getWebpPreviewS3Key()))
            .satisfies(a -> assertThat(a.getWebpPreviewSha256()).as("check webpPreviewSha256").isEqualTo(expected.getWebpPreviewSha256()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getUploadDate()).as("check uploadDate").isEqualTo(expected.getUploadDate()))
            .satisfies(a -> assertThat(a.getIsPublic()).as("check isPublic").isEqualTo(expected.getIsPublic()))
            .satisfies(a -> assertThat(a.getDownloadCount()).as("check downloadCount").isEqualTo(expected.getDownloadCount()))
            .satisfies(a -> assertThat(a.getViewCount()).as("check viewCount").isEqualTo(expected.getViewCount()))
            .satisfies(a -> assertThat(a.getDetectedLanguage()).as("check detectedLanguage").isEqualTo(expected.getDetectedLanguage()))
            .satisfies(a -> assertThat(a.getManualLanguage()).as("check manualLanguage").isEqualTo(expected.getManualLanguage()))
            .satisfies(a ->
                assertThat(a.getLanguageConfidence()).as("check languageConfidence").isEqualTo(expected.getLanguageConfidence())
            )
            .satisfies(a -> assertThat(a.getPageCount()).as("check pageCount").isEqualTo(expected.getPageCount()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentUpdatableRelationshipsEquals(Document expected, Document actual) {
        assertThat(actual)
            .as("Verify Document relationships")
            .satisfies(a -> assertThat(a.getFolder()).as("check folder").isEqualTo(expected.getFolder()))
            .satisfies(a -> assertThat(a.getDocumentType()).as("check documentType").isEqualTo(expected.getDocumentType()));
    }
}
