package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentTagAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTagAllPropertiesEquals(DocumentTag expected, DocumentTag actual) {
        assertDocumentTagAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentTagAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTagAllUpdatablePropertiesEquals(DocumentTag expected, DocumentTag actual) {
        assertDocumentTagUpdatableFieldsEquals(expected, actual);
        assertDocumentTagUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTagAutoGeneratedPropertiesEquals(DocumentTag expected, DocumentTag actual) {
        assertThat(actual)
            .as("Verify DocumentTag auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTagUpdatableFieldsEquals(DocumentTag expected, DocumentTag actual) {
        assertThat(actual)
            .as("Verify DocumentTag relevant properties")
            .satisfies(a -> assertThat(a.getAssignedDate()).as("check assignedDate").isEqualTo(expected.getAssignedDate()))
            .satisfies(a -> assertThat(a.getAssignedBy()).as("check assignedBy").isEqualTo(expected.getAssignedBy()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.getIsAutoMetaTagged()).as("check isAutoMetaTagged").isEqualTo(expected.getIsAutoMetaTagged()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentTagUpdatableRelationshipsEquals(DocumentTag expected, DocumentTag actual) {
        assertThat(actual)
            .as("Verify DocumentTag relationships")
            .satisfies(a -> assertThat(a.getDocument()).as("check document").isEqualTo(expected.getDocument()))
            .satisfies(a -> assertThat(a.getMetaTag()).as("check metaTag").isEqualTo(expected.getMetaTag()));
    }
}
