package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExtractedFieldAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExtractedFieldAllPropertiesEquals(ExtractedField expected, ExtractedField actual) {
        assertExtractedFieldAutoGeneratedPropertiesEquals(expected, actual);
        assertExtractedFieldAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExtractedFieldAllUpdatablePropertiesEquals(ExtractedField expected, ExtractedField actual) {
        assertExtractedFieldUpdatableFieldsEquals(expected, actual);
        assertExtractedFieldUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExtractedFieldAutoGeneratedPropertiesEquals(ExtractedField expected, ExtractedField actual) {
        assertThat(actual)
            .as("Verify ExtractedField auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExtractedFieldUpdatableFieldsEquals(ExtractedField expected, ExtractedField actual) {
        assertThat(actual)
            .as("Verify ExtractedField relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getFieldKey()).as("check fieldKey").isEqualTo(expected.getFieldKey()))
            .satisfies(a -> assertThat(a.getFieldValue()).as("check fieldValue").isEqualTo(expected.getFieldValue()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.getExtractionMethod()).as("check extractionMethod").isEqualTo(expected.getExtractionMethod()))
            .satisfies(a -> assertThat(a.getIsVerified()).as("check isVerified").isEqualTo(expected.getIsVerified()))
            .satisfies(a -> assertThat(a.getExtractedDate()).as("check extractedDate").isEqualTo(expected.getExtractedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExtractedFieldUpdatableRelationshipsEquals(ExtractedField expected, ExtractedField actual) {
        // empty method
    }
}
