package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MetaPermissionGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaPermissionGroupAllPropertiesEquals(MetaPermissionGroup expected, MetaPermissionGroup actual) {
        assertMetaPermissionGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertMetaPermissionGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaPermissionGroupAllUpdatablePropertiesEquals(MetaPermissionGroup expected, MetaPermissionGroup actual) {
        assertMetaPermissionGroupUpdatableFieldsEquals(expected, actual);
        assertMetaPermissionGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaPermissionGroupAutoGeneratedPropertiesEquals(MetaPermissionGroup expected, MetaPermissionGroup actual) {
        assertThat(actual)
            .as("Verify MetaPermissionGroup auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaPermissionGroupUpdatableFieldsEquals(MetaPermissionGroup expected, MetaPermissionGroup actual) {
        assertThat(actual)
            .as("Verify MetaPermissionGroup relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getPermissions()).as("check permissions").isEqualTo(expected.getPermissions()))
            .satisfies(a -> assertThat(a.getIsSystem()).as("check isSystem").isEqualTo(expected.getIsSystem()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetaPermissionGroupUpdatableRelationshipsEquals(MetaPermissionGroup expected, MetaPermissionGroup actual) {
        // empty method
    }
}
