package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PermissionGroupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissionGroupAllPropertiesEquals(PermissionGroup expected, PermissionGroup actual) {
        assertPermissionGroupAutoGeneratedPropertiesEquals(expected, actual);
        assertPermissionGroupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissionGroupAllUpdatablePropertiesEquals(PermissionGroup expected, PermissionGroup actual) {
        assertPermissionGroupUpdatableFieldsEquals(expected, actual);
        assertPermissionGroupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissionGroupAutoGeneratedPropertiesEquals(PermissionGroup expected, PermissionGroup actual) {
        assertThat(actual)
            .as("Verify PermissionGroup auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissionGroupUpdatableFieldsEquals(PermissionGroup expected, PermissionGroup actual) {
        assertThat(actual)
            .as("Verify PermissionGroup relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getPermissions()).as("check permissions").isEqualTo(expected.getPermissions()))
            .satisfies(a -> assertThat(a.getIsSystem()).as("check isSystem").isEqualTo(expected.getIsSystem()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermissionGroupUpdatableRelationshipsEquals(PermissionGroup expected, PermissionGroup actual) {
        // empty method
    }
}
