package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SavedSearchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSavedSearchAllPropertiesEquals(SavedSearch expected, SavedSearch actual) {
        assertSavedSearchAutoGeneratedPropertiesEquals(expected, actual);
        assertSavedSearchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSavedSearchAllUpdatablePropertiesEquals(SavedSearch expected, SavedSearch actual) {
        assertSavedSearchUpdatableFieldsEquals(expected, actual);
        assertSavedSearchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSavedSearchAutoGeneratedPropertiesEquals(SavedSearch expected, SavedSearch actual) {
        assertThat(actual)
            .as("Verify SavedSearch auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSavedSearchUpdatableFieldsEquals(SavedSearch expected, SavedSearch actual) {
        assertThat(actual)
            .as("Verify SavedSearch relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getQuery()).as("check query").isEqualTo(expected.getQuery()))
            .satisfies(a -> assertThat(a.getIsPublic()).as("check isPublic").isEqualTo(expected.getIsPublic()))
            .satisfies(a -> assertThat(a.getIsAlert()).as("check isAlert").isEqualTo(expected.getIsAlert()))
            .satisfies(a -> assertThat(a.getAlertFrequency()).as("check alertFrequency").isEqualTo(expected.getAlertFrequency()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSavedSearchUpdatableRelationshipsEquals(SavedSearch expected, SavedSearch actual) {
        // empty method
    }
}
