package fr.smartprod.paperdms.document.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SmartFolderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSmartFolderAllPropertiesEquals(SmartFolder expected, SmartFolder actual) {
        assertSmartFolderAutoGeneratedPropertiesEquals(expected, actual);
        assertSmartFolderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSmartFolderAllUpdatablePropertiesEquals(SmartFolder expected, SmartFolder actual) {
        assertSmartFolderUpdatableFieldsEquals(expected, actual);
        assertSmartFolderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSmartFolderAutoGeneratedPropertiesEquals(SmartFolder expected, SmartFolder actual) {
        assertThat(actual)
            .as("Verify SmartFolder auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSmartFolderUpdatableFieldsEquals(SmartFolder expected, SmartFolder actual) {
        assertThat(actual)
            .as("Verify SmartFolder relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getQueryJson()).as("check queryJson").isEqualTo(expected.getQueryJson()))
            .satisfies(a -> assertThat(a.getAutoRefresh()).as("check autoRefresh").isEqualTo(expected.getAutoRefresh()))
            .satisfies(a -> assertThat(a.getIsPublic()).as("check isPublic").isEqualTo(expected.getIsPublic()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSmartFolderUpdatableRelationshipsEquals(SmartFolder expected, SmartFolder actual) {
        // empty method
    }
}
