package fr.smartprod.paperdms.search.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SearchIndexAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchIndexAllPropertiesEquals(SearchIndex expected, SearchIndex actual) {
        assertSearchIndexAutoGeneratedPropertiesEquals(expected, actual);
        assertSearchIndexAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchIndexAllUpdatablePropertiesEquals(SearchIndex expected, SearchIndex actual) {
        assertSearchIndexUpdatableFieldsEquals(expected, actual);
        assertSearchIndexUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchIndexAutoGeneratedPropertiesEquals(SearchIndex expected, SearchIndex actual) {
        assertThat(actual)
            .as("Verify SearchIndex auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchIndexUpdatableFieldsEquals(SearchIndex expected, SearchIndex actual) {
        assertThat(actual)
            .as("Verify SearchIndex relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getIndexedContent()).as("check indexedContent").isEqualTo(expected.getIndexedContent()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()))
            .satisfies(a -> assertThat(a.getTags()).as("check tags").isEqualTo(expected.getTags()))
            .satisfies(a -> assertThat(a.getCorrespondents()).as("check correspondents").isEqualTo(expected.getCorrespondents()))
            .satisfies(a -> assertThat(a.getExtractedEntities()).as("check extractedEntities").isEqualTo(expected.getExtractedEntities()))
            .satisfies(a -> assertThat(a.getIndexedDate()).as("check indexedDate").isEqualTo(expected.getIndexedDate()))
            .satisfies(a -> assertThat(a.getLastUpdated()).as("check lastUpdated").isEqualTo(expected.getLastUpdated()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchIndexUpdatableRelationshipsEquals(SearchIndex expected, SearchIndex actual) {
        // empty method
    }
}
