package fr.smartprod.paperdms.search.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SearchFacetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchFacetAllPropertiesEquals(SearchFacet expected, SearchFacet actual) {
        assertSearchFacetAutoGeneratedPropertiesEquals(expected, actual);
        assertSearchFacetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchFacetAllUpdatablePropertiesEquals(SearchFacet expected, SearchFacet actual) {
        assertSearchFacetUpdatableFieldsEquals(expected, actual);
        assertSearchFacetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchFacetAutoGeneratedPropertiesEquals(SearchFacet expected, SearchFacet actual) {
        assertThat(actual)
            .as("Verify SearchFacet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchFacetUpdatableFieldsEquals(SearchFacet expected, SearchFacet actual) {
        assertThat(actual)
            .as("Verify SearchFacet relevant properties")
            .satisfies(a -> assertThat(a.getFacetName()).as("check facetName").isEqualTo(expected.getFacetName()))
            .satisfies(a -> assertThat(a.getFacetType()).as("check facetType").isEqualTo(expected.getFacetType()))
            .satisfies(a -> assertThat(a.getValues()).as("check values").isEqualTo(expected.getValues()))
            .satisfies(a -> assertThat(a.getCounts()).as("check counts").isEqualTo(expected.getCounts()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchFacetUpdatableRelationshipsEquals(SearchFacet expected, SearchFacet actual) {
        assertThat(actual)
            .as("Verify SearchFacet relationships")
            .satisfies(a -> assertThat(a.getSearchQuery()).as("check searchQuery").isEqualTo(expected.getSearchQuery()));
    }
}
