package fr.smartprod.paperdms.search.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SemanticSearchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSemanticSearchAllPropertiesEquals(SemanticSearch expected, SemanticSearch actual) {
        assertSemanticSearchAutoGeneratedPropertiesEquals(expected, actual);
        assertSemanticSearchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSemanticSearchAllUpdatablePropertiesEquals(SemanticSearch expected, SemanticSearch actual) {
        assertSemanticSearchUpdatableFieldsEquals(expected, actual);
        assertSemanticSearchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSemanticSearchAutoGeneratedPropertiesEquals(SemanticSearch expected, SemanticSearch actual) {
        assertThat(actual)
            .as("Verify SemanticSearch auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSemanticSearchUpdatableFieldsEquals(SemanticSearch expected, SemanticSearch actual) {
        assertThat(actual)
            .as("Verify SemanticSearch relevant properties")
            .satisfies(a -> assertThat(a.getQuery()).as("check query").isEqualTo(expected.getQuery()))
            .satisfies(a -> assertThat(a.getQueryEmbedding()).as("check queryEmbedding").isEqualTo(expected.getQueryEmbedding()))
            .satisfies(a -> assertThat(a.getResults()).as("check results").isEqualTo(expected.getResults()))
            .satisfies(a -> assertThat(a.getRelevanceScores()).as("check relevanceScores").isEqualTo(expected.getRelevanceScores()))
            .satisfies(a -> assertThat(a.getModelUsed()).as("check modelUsed").isEqualTo(expected.getModelUsed()))
            .satisfies(a -> assertThat(a.getExecutionTime()).as("check executionTime").isEqualTo(expected.getExecutionTime()))
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getSearchDate()).as("check searchDate").isEqualTo(expected.getSearchDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSemanticSearchUpdatableRelationshipsEquals(SemanticSearch expected, SemanticSearch actual) {
        // empty method
    }
}
