package fr.smartprod.paperdms.transform.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RedactionJobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedactionJobAllPropertiesEquals(RedactionJob expected, RedactionJob actual) {
        assertRedactionJobAutoGeneratedPropertiesEquals(expected, actual);
        assertRedactionJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedactionJobAllUpdatablePropertiesEquals(RedactionJob expected, RedactionJob actual) {
        assertRedactionJobUpdatableFieldsEquals(expected, actual);
        assertRedactionJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedactionJobAutoGeneratedPropertiesEquals(RedactionJob expected, RedactionJob actual) {
        assertThat(actual)
            .as("Verify RedactionJob auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedactionJobUpdatableFieldsEquals(RedactionJob expected, RedactionJob actual) {
        assertThat(actual)
            .as("Verify RedactionJob relevant properties")
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getRedactionAreas()).as("check redactionAreas").isEqualTo(expected.getRedactionAreas()))
            .satisfies(a -> assertThat(a.getRedactionType()).as("check redactionType").isEqualTo(expected.getRedactionType()))
            .satisfies(a -> assertThat(a.getRedactionColor()).as("check redactionColor").isEqualTo(expected.getRedactionColor()))
            .satisfies(a -> assertThat(a.getReplaceWith()).as("check replaceWith").isEqualTo(expected.getReplaceWith()))
            .satisfies(a -> assertThat(a.getOutputS3Key()).as("check outputS3Key").isEqualTo(expected.getOutputS3Key()))
            .satisfies(a -> assertThat(a.getOutputDocumentId()).as("check outputDocumentId").isEqualTo(expected.getOutputDocumentId()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedactionJobUpdatableRelationshipsEquals(RedactionJob expected, RedactionJob actual) {
        // empty method
    }
}
