package fr.smartprod.paperdms.transform.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransformMergeJobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformMergeJobAllPropertiesEquals(TransformMergeJob expected, TransformMergeJob actual) {
        assertTransformMergeJobAutoGeneratedPropertiesEquals(expected, actual);
        assertTransformMergeJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformMergeJobAllUpdatablePropertiesEquals(TransformMergeJob expected, TransformMergeJob actual) {
        assertTransformMergeJobUpdatableFieldsEquals(expected, actual);
        assertTransformMergeJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformMergeJobAutoGeneratedPropertiesEquals(TransformMergeJob expected, TransformMergeJob actual) {
        assertThat(actual)
            .as("Verify TransformMergeJob auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformMergeJobUpdatableFieldsEquals(TransformMergeJob expected, TransformMergeJob actual) {
        assertThat(actual)
            .as("Verify TransformMergeJob relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a ->
                assertThat(a.getSourceDocumentSha256()).as("check sourceDocumentSha256").isEqualTo(expected.getSourceDocumentSha256())
            )
            .satisfies(a -> assertThat(a.getMergeOrder()).as("check mergeOrder").isEqualTo(expected.getMergeOrder()))
            .satisfies(a -> assertThat(a.getIncludeBookmarks()).as("check includeBookmarks").isEqualTo(expected.getIncludeBookmarks()))
            .satisfies(a -> assertThat(a.getIncludeToc()).as("check includeToc").isEqualTo(expected.getIncludeToc()))
            .satisfies(a -> assertThat(a.getAddPageNumbers()).as("check addPageNumbers").isEqualTo(expected.getAddPageNumbers()))
            .satisfies(a -> assertThat(a.getOutputS3Key()).as("check outputS3Key").isEqualTo(expected.getOutputS3Key()))
            .satisfies(a ->
                assertThat(a.getOutputDocumentSha256()).as("check outputDocumentSha256").isEqualTo(expected.getOutputDocumentSha256())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformMergeJobUpdatableRelationshipsEquals(TransformMergeJob expected, TransformMergeJob actual) {
        // empty method
    }
}
