package fr.smartprod.paperdms.gateway.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentProcessAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentProcessAllPropertiesEquals(DocumentProcess expected, DocumentProcess actual) {
        assertDocumentProcessAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentProcessAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentProcessAllUpdatablePropertiesEquals(DocumentProcess expected, DocumentProcess actual) {
        assertDocumentProcessUpdatableFieldsEquals(expected, actual);
        assertDocumentProcessUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentProcessAutoGeneratedPropertiesEquals(DocumentProcess expected, DocumentProcess actual) {
        assertThat(actual)
            .as("Verify DocumentProcess auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentProcessUpdatableFieldsEquals(DocumentProcess expected, DocumentProcess actual) {
        assertThat(actual)
            .as("Verify DocumentProcess relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentProcessUpdatableRelationshipsEquals(DocumentProcess expected, DocumentProcess actual) {
        // empty method
    }
}
