package com.ged.workflow.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WorkflowStepAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowStepAllPropertiesEquals(WorkflowStep expected, WorkflowStep actual) {
        assertWorkflowStepAutoGeneratedPropertiesEquals(expected, actual);
        assertWorkflowStepAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowStepAllUpdatablePropertiesEquals(WorkflowStep expected, WorkflowStep actual) {
        assertWorkflowStepUpdatableFieldsEquals(expected, actual);
        assertWorkflowStepUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowStepAutoGeneratedPropertiesEquals(WorkflowStep expected, WorkflowStep actual) {
        assertThat(actual)
            .as("Verify WorkflowStep auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowStepUpdatableFieldsEquals(WorkflowStep expected, WorkflowStep actual) {
        assertThat(actual)
            .as("Verify WorkflowStep relevant properties")
            .satisfies(a -> assertThat(a.getStepNumber()).as("check stepNumber").isEqualTo(expected.getStepNumber()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStepType()).as("check stepType").isEqualTo(expected.getStepType()))
            .satisfies(a -> assertThat(a.getAssigneeType()).as("check assigneeType").isEqualTo(expected.getAssigneeType()))
            .satisfies(a -> assertThat(a.getAssigneeId()).as("check assigneeId").isEqualTo(expected.getAssigneeId()))
            .satisfies(a -> assertThat(a.getAssigneeGroup()).as("check assigneeGroup").isEqualTo(expected.getAssigneeGroup()))
            .satisfies(a -> assertThat(a.getDueInDays()).as("check dueInDays").isEqualTo(expected.getDueInDays()))
            .satisfies(a -> assertThat(a.getIsRequired()).as("check isRequired").isEqualTo(expected.getIsRequired()))
            .satisfies(a -> assertThat(a.getCanDelegate()).as("check canDelegate").isEqualTo(expected.getCanDelegate()))
            .satisfies(a -> assertThat(a.getCanReject()).as("check canReject").isEqualTo(expected.getCanReject()))
            .satisfies(a -> assertThat(a.getConfiguration()).as("check configuration").isEqualTo(expected.getConfiguration()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkflowStepUpdatableRelationshipsEquals(WorkflowStep expected, WorkflowStep actual) {
        assertThat(actual)
            .as("Verify WorkflowStep relationships")
            .satisfies(a -> assertThat(a.getWorkflow()).as("check workflow").isEqualTo(expected.getWorkflow()));
    }
}
