package fr.smartprod.paperdms.reporting.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReportingSystemMetricAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingSystemMetricAllPropertiesEquals(ReportingSystemMetric expected, ReportingSystemMetric actual) {
        assertReportingSystemMetricAutoGeneratedPropertiesEquals(expected, actual);
        assertReportingSystemMetricAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingSystemMetricAllUpdatablePropertiesEquals(
        ReportingSystemMetric expected,
        ReportingSystemMetric actual
    ) {
        assertReportingSystemMetricUpdatableFieldsEquals(expected, actual);
        assertReportingSystemMetricUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingSystemMetricAutoGeneratedPropertiesEquals(
        ReportingSystemMetric expected,
        ReportingSystemMetric actual
    ) {
        assertThat(actual)
            .as("Verify ReportingSystemMetric auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingSystemMetricUpdatableFieldsEquals(ReportingSystemMetric expected, ReportingSystemMetric actual) {
        assertThat(actual)
            .as("Verify ReportingSystemMetric relevant properties")
            .satisfies(a -> assertThat(a.getMetricName()).as("check metricName").isEqualTo(expected.getMetricName()))
            .satisfies(a -> assertThat(a.getCpuUsage()).as("check cpuUsage").isEqualTo(expected.getCpuUsage()))
            .satisfies(a -> assertThat(a.getMemoryUsage()).as("check memoryUsage").isEqualTo(expected.getMemoryUsage()))
            .satisfies(a -> assertThat(a.getDiskUsage()).as("check diskUsage").isEqualTo(expected.getDiskUsage()))
            .satisfies(a -> assertThat(a.getNetworkIn()).as("check networkIn").isEqualTo(expected.getNetworkIn()))
            .satisfies(a -> assertThat(a.getNetworkOut()).as("check networkOut").isEqualTo(expected.getNetworkOut()))
            .satisfies(a -> assertThat(a.getActiveConnections()).as("check activeConnections").isEqualTo(expected.getActiveConnections()))
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingSystemMetricUpdatableRelationshipsEquals(
        ReportingSystemMetric expected,
        ReportingSystemMetric actual
    ) {
        // empty method
    }
}
