package fr.smartprod.paperdms.reporting.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReportingDashboardWidgetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingDashboardWidgetAllPropertiesEquals(
        ReportingDashboardWidget expected,
        ReportingDashboardWidget actual
    ) {
        assertReportingDashboardWidgetAutoGeneratedPropertiesEquals(expected, actual);
        assertReportingDashboardWidgetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingDashboardWidgetAllUpdatablePropertiesEquals(
        ReportingDashboardWidget expected,
        ReportingDashboardWidget actual
    ) {
        assertReportingDashboardWidgetUpdatableFieldsEquals(expected, actual);
        assertReportingDashboardWidgetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingDashboardWidgetAutoGeneratedPropertiesEquals(
        ReportingDashboardWidget expected,
        ReportingDashboardWidget actual
    ) {
        assertThat(actual)
            .as("Verify ReportingDashboardWidget auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingDashboardWidgetUpdatableFieldsEquals(
        ReportingDashboardWidget expected,
        ReportingDashboardWidget actual
    ) {
        assertThat(actual)
            .as("Verify ReportingDashboardWidget relevant properties")
            .satisfies(a -> assertThat(a.getWidgetType()).as("check widgetType").isEqualTo(expected.getWidgetType()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getConfiguration()).as("check configuration").isEqualTo(expected.getConfiguration()))
            .satisfies(a -> assertThat(a.getDataSource()).as("check dataSource").isEqualTo(expected.getDataSource()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getSizeX()).as("check sizeX").isEqualTo(expected.getSizeX()))
            .satisfies(a -> assertThat(a.getSizeY()).as("check sizeY").isEqualTo(expected.getSizeY()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingDashboardWidgetUpdatableRelationshipsEquals(
        ReportingDashboardWidget expected,
        ReportingDashboardWidget actual
    ) {
        assertThat(actual)
            .as("Verify ReportingDashboardWidget relationships")
            .satisfies(a -> assertThat(a.getDashboar()).as("check dashboar").isEqualTo(expected.getDashboar()));
    }
}
