package fr.smartprod.paperdms.reporting.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReportingScheduledReportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingScheduledReportAllPropertiesEquals(
        ReportingScheduledReport expected,
        ReportingScheduledReport actual
    ) {
        assertReportingScheduledReportAutoGeneratedPropertiesEquals(expected, actual);
        assertReportingScheduledReportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingScheduledReportAllUpdatablePropertiesEquals(
        ReportingScheduledReport expected,
        ReportingScheduledReport actual
    ) {
        assertReportingScheduledReportUpdatableFieldsEquals(expected, actual);
        assertReportingScheduledReportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingScheduledReportAutoGeneratedPropertiesEquals(
        ReportingScheduledReport expected,
        ReportingScheduledReport actual
    ) {
        assertThat(actual)
            .as("Verify ReportingScheduledReport auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingScheduledReportUpdatableFieldsEquals(
        ReportingScheduledReport expected,
        ReportingScheduledReport actual
    ) {
        assertThat(actual)
            .as("Verify ReportingScheduledReport relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getReportType()).as("check reportType").isEqualTo(expected.getReportType()))
            .satisfies(a -> assertThat(a.getQuery()).as("check query").isEqualTo(expected.getQuery()))
            .satisfies(a -> assertThat(a.getSchedule()).as("check schedule").isEqualTo(expected.getSchedule()))
            .satisfies(a -> assertThat(a.getFormat()).as("check format").isEqualTo(expected.getFormat()))
            .satisfies(a -> assertThat(a.getRecipients()).as("check recipients").isEqualTo(expected.getRecipients()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getLastRun()).as("check lastRun").isEqualTo(expected.getLastRun()))
            .satisfies(a -> assertThat(a.getNextRun()).as("check nextRun").isEqualTo(expected.getNextRun()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingScheduledReportUpdatableRelationshipsEquals(
        ReportingScheduledReport expected,
        ReportingScheduledReport actual
    ) {
        // empty method
    }
}
