package fr.smartprod.paperdms.reporting.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReportingExecutionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingExecutionAllPropertiesEquals(ReportingExecution expected, ReportingExecution actual) {
        assertReportingExecutionAutoGeneratedPropertiesEquals(expected, actual);
        assertReportingExecutionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingExecutionAllUpdatablePropertiesEquals(ReportingExecution expected, ReportingExecution actual) {
        assertReportingExecutionUpdatableFieldsEquals(expected, actual);
        assertReportingExecutionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingExecutionAutoGeneratedPropertiesEquals(ReportingExecution expected, ReportingExecution actual) {
        assertThat(actual)
            .as("Verify ReportingExecution auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingExecutionUpdatableFieldsEquals(ReportingExecution expected, ReportingExecution actual) {
        assertThat(actual)
            .as("Verify ReportingExecution relevant properties")
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getRecordsProcessed()).as("check recordsProcessed").isEqualTo(expected.getRecordsProcessed()))
            .satisfies(a -> assertThat(a.getOutputS3Key()).as("check outputS3Key").isEqualTo(expected.getOutputS3Key()))
            .satisfies(a -> assertThat(a.getOutputSize()).as("check outputSize").isEqualTo(expected.getOutputSize()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReportingExecutionUpdatableRelationshipsEquals(ReportingExecution expected, ReportingExecution actual) {
        assertThat(actual)
            .as("Verify ReportingExecution relationships")
            .satisfies(a -> assertThat(a.getScheduledReport()).as("check scheduledReport").isEqualTo(expected.getScheduledReport()));
    }
}
