package fr.smartprod.paperdms.export.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExportResultAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportResultAllPropertiesEquals(ExportResult expected, ExportResult actual) {
        assertExportResultAutoGeneratedPropertiesEquals(expected, actual);
        assertExportResultAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportResultAllUpdatablePropertiesEquals(ExportResult expected, ExportResult actual) {
        assertExportResultUpdatableFieldsEquals(expected, actual);
        assertExportResultUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportResultAutoGeneratedPropertiesEquals(ExportResult expected, ExportResult actual) {
        assertThat(actual)
            .as("Verify ExportResult auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportResultUpdatableFieldsEquals(ExportResult expected, ExportResult actual) {
        assertThat(actual)
            .as("Verify ExportResult relevant properties")
            .satisfies(a -> assertThat(a.getExportJobId()).as("check exportJobId").isEqualTo(expected.getExportJobId()))
            .satisfies(a -> assertThat(a.getDocumentId()).as("check documentId").isEqualTo(expected.getDocumentId()))
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()))
            .satisfies(a -> assertThat(a.getOriginalFileName()).as("check originalFileName").isEqualTo(expected.getOriginalFileName()))
            .satisfies(a -> assertThat(a.getExportedPath()).as("check exportedPath").isEqualTo(expected.getExportedPath()))
            .satisfies(a -> assertThat(a.getExportedFileName()).as("check exportedFileName").isEqualTo(expected.getExportedFileName()))
            .satisfies(a -> assertThat(a.gets3ExportKey()).as("check s3ExportKey").isEqualTo(expected.gets3ExportKey()))
            .satisfies(a -> assertThat(a.getFileSize()).as("check fileSize").isEqualTo(expected.getFileSize()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getExportedDate()).as("check exportedDate").isEqualTo(expected.getExportedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportResultUpdatableRelationshipsEquals(ExportResult expected, ExportResult actual) {
        assertThat(actual)
            .as("Verify ExportResult relationships")
            .satisfies(a -> assertThat(a.getExportJob()).as("check exportJob").isEqualTo(expected.getExportJob()));
    }
}
