package fr.smartprod.paperdms.export.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExportJobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportJobAllPropertiesEquals(ExportJob expected, ExportJob actual) {
        assertExportJobAutoGeneratedPropertiesEquals(expected, actual);
        assertExportJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportJobAllUpdatablePropertiesEquals(ExportJob expected, ExportJob actual) {
        assertExportJobUpdatableFieldsEquals(expected, actual);
        assertExportJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportJobAutoGeneratedPropertiesEquals(ExportJob expected, ExportJob actual) {
        assertThat(actual)
            .as("Verify ExportJob auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportJobUpdatableFieldsEquals(ExportJob expected, ExportJob actual) {
        assertThat(actual)
            .as("Verify ExportJob relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getDocumentQuery()).as("check documentQuery").isEqualTo(expected.getDocumentQuery()))
            .satisfies(a -> assertThat(a.getExportPatternId()).as("check exportPatternId").isEqualTo(expected.getExportPatternId()))
            .satisfies(a -> assertThat(a.getExportFormat()).as("check exportFormat").isEqualTo(expected.getExportFormat()))
            .satisfies(a -> assertThat(a.getIncludeMetadata()).as("check includeMetadata").isEqualTo(expected.getIncludeMetadata()))
            .satisfies(a -> assertThat(a.getIncludeVersions()).as("check includeVersions").isEqualTo(expected.getIncludeVersions()))
            .satisfies(a -> assertThat(a.getIncludeComments()).as("check includeComments").isEqualTo(expected.getIncludeComments()))
            .satisfies(a -> assertThat(a.getIncludeAuditTrail()).as("check includeAuditTrail").isEqualTo(expected.getIncludeAuditTrail()))
            .satisfies(a -> assertThat(a.gets3ExportKey()).as("check s3ExportKey").isEqualTo(expected.gets3ExportKey()))
            .satisfies(a -> assertThat(a.getExportSize()).as("check exportSize").isEqualTo(expected.getExportSize()))
            .satisfies(a -> assertThat(a.getDocumentCount()).as("check documentCount").isEqualTo(expected.getDocumentCount()))
            .satisfies(a -> assertThat(a.getFilesGenerated()).as("check filesGenerated").isEqualTo(expected.getFilesGenerated()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExportJobUpdatableRelationshipsEquals(ExportJob expected, ExportJob actual) {
        assertThat(actual)
            .as("Verify ExportJob relationships")
            .satisfies(a -> assertThat(a.getExportPattern()).as("check exportPattern").isEqualTo(expected.getExportPattern()));
    }
}
