package fr.smartprod.paperdms.transform.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransformCompressionJobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformCompressionJobAllPropertiesEquals(TransformCompressionJob expected, TransformCompressionJob actual) {
        assertTransformCompressionJobAutoGeneratedPropertiesEquals(expected, actual);
        assertTransformCompressionJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformCompressionJobAllUpdatablePropertiesEquals(
        TransformCompressionJob expected,
        TransformCompressionJob actual
    ) {
        assertTransformCompressionJobUpdatableFieldsEquals(expected, actual);
        assertTransformCompressionJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformCompressionJobAutoGeneratedPropertiesEquals(
        TransformCompressionJob expected,
        TransformCompressionJob actual
    ) {
        assertThat(actual)
            .as("Verify TransformCompressionJob auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformCompressionJobUpdatableFieldsEquals(
        TransformCompressionJob expected,
        TransformCompressionJob actual
    ) {
        assertThat(actual)
            .as("Verify TransformCompressionJob relevant properties")
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()))
            .satisfies(a -> assertThat(a.getCompressionType()).as("check compressionType").isEqualTo(expected.getCompressionType()))
            .satisfies(a -> assertThat(a.getQuality()).as("check quality").isEqualTo(expected.getQuality()))
            .satisfies(a -> assertThat(a.getTargetSizeKb()).as("check targetSizeKb").isEqualTo(expected.getTargetSizeKb()))
            .satisfies(a -> assertThat(a.getOriginalSize()).as("check originalSize").isEqualTo(expected.getOriginalSize()))
            .satisfies(a -> assertThat(a.getCompressedSize()).as("check compressedSize").isEqualTo(expected.getCompressedSize()))
            .satisfies(a -> assertThat(a.getCompressionRatio()).as("check compressionRatio").isEqualTo(expected.getCompressionRatio()))
            .satisfies(a -> assertThat(a.getOutputS3Key()).as("check outputS3Key").isEqualTo(expected.getOutputS3Key()))
            .satisfies(a ->
                assertThat(a.getOutputDocumentSha256()).as("check outputDocumentSha256").isEqualTo(expected.getOutputDocumentSha256())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformCompressionJobUpdatableRelationshipsEquals(
        TransformCompressionJob expected,
        TransformCompressionJob actual
    ) {
        // empty method
    }
}
