package fr.smartprod.paperdms.transform.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransformWatermarkJobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformWatermarkJobAllPropertiesEquals(TransformWatermarkJob expected, TransformWatermarkJob actual) {
        assertTransformWatermarkJobAutoGeneratedPropertiesEquals(expected, actual);
        assertTransformWatermarkJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformWatermarkJobAllUpdatablePropertiesEquals(
        TransformWatermarkJob expected,
        TransformWatermarkJob actual
    ) {
        assertTransformWatermarkJobUpdatableFieldsEquals(expected, actual);
        assertTransformWatermarkJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformWatermarkJobAutoGeneratedPropertiesEquals(
        TransformWatermarkJob expected,
        TransformWatermarkJob actual
    ) {
        assertThat(actual)
            .as("Verify TransformWatermarkJob auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformWatermarkJobUpdatableFieldsEquals(TransformWatermarkJob expected, TransformWatermarkJob actual) {
        assertThat(actual)
            .as("Verify TransformWatermarkJob relevant properties")
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()))
            .satisfies(a -> assertThat(a.getWatermarkType()).as("check watermarkType").isEqualTo(expected.getWatermarkType()))
            .satisfies(a -> assertThat(a.getWatermarkText()).as("check watermarkText").isEqualTo(expected.getWatermarkText()))
            .satisfies(a ->
                assertThat(a.getWatermarkImageS3Key()).as("check watermarkImageS3Key").isEqualTo(expected.getWatermarkImageS3Key())
            )
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getOpacity()).as("check opacity").isEqualTo(expected.getOpacity()))
            .satisfies(a -> assertThat(a.getFontSize()).as("check fontSize").isEqualTo(expected.getFontSize()))
            .satisfies(a -> assertThat(a.getColor()).as("check color").isEqualTo(expected.getColor()))
            .satisfies(a -> assertThat(a.getRotation()).as("check rotation").isEqualTo(expected.getRotation()))
            .satisfies(a -> assertThat(a.getTiled()).as("check tiled").isEqualTo(expected.getTiled()))
            .satisfies(a -> assertThat(a.getOutputS3Key()).as("check outputS3Key").isEqualTo(expected.getOutputS3Key()))
            .satisfies(a ->
                assertThat(a.getOutputDocumentSha256()).as("check outputDocumentSha256").isEqualTo(expected.getOutputDocumentSha256())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformWatermarkJobUpdatableRelationshipsEquals(
        TransformWatermarkJob expected,
        TransformWatermarkJob actual
    ) {
        // empty method
    }
}
