package fr.smartprod.paperdms.transform.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransformConversionJobAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformConversionJobAllPropertiesEquals(TransformConversionJob expected, TransformConversionJob actual) {
        assertTransformConversionJobAutoGeneratedPropertiesEquals(expected, actual);
        assertTransformConversionJobAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformConversionJobAllUpdatablePropertiesEquals(
        TransformConversionJob expected,
        TransformConversionJob actual
    ) {
        assertTransformConversionJobUpdatableFieldsEquals(expected, actual);
        assertTransformConversionJobUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformConversionJobAutoGeneratedPropertiesEquals(
        TransformConversionJob expected,
        TransformConversionJob actual
    ) {
        assertThat(actual)
            .as("Verify TransformConversionJob auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformConversionJobUpdatableFieldsEquals(TransformConversionJob expected, TransformConversionJob actual) {
        assertThat(actual)
            .as("Verify TransformConversionJob relevant properties")
            .satisfies(a -> assertThat(a.getDocumentSha256()).as("check documentSha256").isEqualTo(expected.getDocumentSha256()))
            .satisfies(a -> assertThat(a.getSourceFormat()).as("check sourceFormat").isEqualTo(expected.getSourceFormat()))
            .satisfies(a -> assertThat(a.getTargetFormat()).as("check targetFormat").isEqualTo(expected.getTargetFormat()))
            .satisfies(a -> assertThat(a.getConversionEngine()).as("check conversionEngine").isEqualTo(expected.getConversionEngine()))
            .satisfies(a -> assertThat(a.getOptions()).as("check options").isEqualTo(expected.getOptions()))
            .satisfies(a -> assertThat(a.getOutputS3Key()).as("check outputS3Key").isEqualTo(expected.getOutputS3Key()))
            .satisfies(a ->
                assertThat(a.getOutputDocumentSha256()).as("check outputDocumentSha256").isEqualTo(expected.getOutputDocumentSha256())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransformConversionJobUpdatableRelationshipsEquals(
        TransformConversionJob expected,
        TransformConversionJob actual
    ) {
        // empty method
    }
}
